/**
 * Tree domain objects
 * Tree domain objects
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare type TreeNodeKind = 'entry' | 'association' | 'reference';
export declare const TreeNodeKind: {
    Entry: TreeNodeKind;
    Association: TreeNodeKind;
    Reference: TreeNodeKind;
};
