/*
 * Security api
 * Security api...
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.security.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * OAuthClientProperties
 */
@JsonPropertyOrder({
  OAuthClientProperties.URI,
  OAuthClientProperties.REGISTRATION_ID,
  OAuthClientProperties.CLIENT_ID,
  OAuthClientProperties.CLIENT_SECRET,
  OAuthClientProperties.CLIENT_NAME,
  OAuthClientProperties.AUTHORIZATION_URI,
  OAuthClientProperties.TOKEN_URI,
  OAuthClientProperties.USER_INFO_URI,
  OAuthClientProperties.JWK_SET_URI,
  OAuthClientProperties.ISSUER_URI,
  OAuthClientProperties.REDIRECT_URI,
  OAuthClientProperties.SCOPE,
  OAuthClientProperties.AUTHORIZATION_GRANT_TYPE,
  OAuthClientProperties.USER_NAME_ATTRIBUTE,
  OAuthClientProperties.USER_INFO_AUTHENTICATION_METHOD,
  OAuthClientProperties.COMMON_PROVIDER,
  OAuthClientProperties.LOGOUT_OIDC_ENABLED,
  OAuthClientProperties.LOGOUT_END_SESSION_ENDPOINT,
  OAuthClientProperties.LOGOUT_REDIRECT_PATH,
  OAuthClientProperties.LABEL,
  OAuthClientProperties.LOGO,
  OAuthClientProperties.USER_PARAMETER_MAPPING,
  OAuthClientProperties.IS_USER_WITHOUT_GROUP_ALLOWED_TO_LOG_IN,
  OAuthClientProperties.DEFAULT_GROUP_NAME,
  OAuthClientProperties.ROLE_ATTRIBUTES,
  OAuthClientProperties.ROLE_MAPPING,
  OAuthClientProperties.CLIENT_AUTHENTICATION_METHOD,
  OAuthClientProperties.IS_PKCE_ENABLED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class OAuthClientProperties {
  public static final String URI = "uri";
  private URI uri;

  public static final String REGISTRATION_ID = "registrationId";
  private String registrationId;

  public static final String CLIENT_ID = "clientId";
  private String clientId;

  public static final String CLIENT_SECRET = "clientSecret";
  private String clientSecret;

  public static final String CLIENT_NAME = "clientName";
  private String clientName;

  public static final String AUTHORIZATION_URI = "authorizationUri";
  private String authorizationUri;

  public static final String TOKEN_URI = "tokenUri";
  private String tokenUri;

  public static final String USER_INFO_URI = "userInfoUri";
  private String userInfoUri;

  public static final String JWK_SET_URI = "jwkSetUri";
  private String jwkSetUri;

  public static final String ISSUER_URI = "issuerUri";
  private String issuerUri;

  public static final String REDIRECT_URI = "redirectUri";
  private String redirectUri = "{baseUrl}/{action}/oauth2/code/{registrationId}";

  public static final String SCOPE = "scope";
  private String scope;

  public static final String AUTHORIZATION_GRANT_TYPE = "authorizationGrantType";
  private String authorizationGrantType;

  public static final String USER_NAME_ATTRIBUTE = "userNameAttribute";
  private String userNameAttribute;

  public static final String USER_INFO_AUTHENTICATION_METHOD = "userInfoAuthenticationMethod";
  private String userInfoAuthenticationMethod;

  public static final String COMMON_PROVIDER = "commonProvider";
  private String commonProvider;

  public static final String LOGOUT_OIDC_ENABLED = "logoutOidcEnabled";
  private Boolean logoutOidcEnabled;

  public static final String LOGOUT_END_SESSION_ENDPOINT = "logoutEndSessionEndpoint";
  private String logoutEndSessionEndpoint;

  public static final String LOGOUT_REDIRECT_PATH = "logoutRedirectPath";
  private String logoutRedirectPath;

  public static final String LABEL = "label";
  private String label;

  public static final String LOGO = "logo";
  private String logo;

  public static final String USER_PARAMETER_MAPPING = "userParameterMapping";
  private Map<String, String> userParameterMapping = new HashMap<>();

  public static final String IS_USER_WITHOUT_GROUP_ALLOWED_TO_LOG_IN = "isUserWithoutGroupAllowedToLogIn";
  private Boolean isUserWithoutGroupAllowedToLogIn = false;

  public static final String DEFAULT_GROUP_NAME = "defaultGroupName";
  private String defaultGroupName;

  public static final String ROLE_ATTRIBUTES = "roleAttributes";
  private List<String> roleAttributes = new ArrayList<>();

  public static final String ROLE_MAPPING = "roleMapping";
  private Map<String, String> roleMapping = new HashMap<>();

  public static final String CLIENT_AUTHENTICATION_METHOD = "clientAuthenticationMethod";
  private String clientAuthenticationMethod = "client_secret_basic";

  public static final String IS_PKCE_ENABLED = "isPkceEnabled";
  private Boolean isPkceEnabled = false;

  public OAuthClientProperties() {
  }

  public OAuthClientProperties uri(URI uri) {
    
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   * @return uri
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUri() {
    return uri;
  }


  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(URI uri) {
    this.uri = uri;
  }

  public OAuthClientProperties registrationId(String registrationId) {
    
    this.registrationId = registrationId;
    return this;
  }

  /**
   * The registration identifier that app uses to identify the client registration
   * @return registrationId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The registration identifier that app uses to identify the client registration")
  @JsonProperty(REGISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRegistrationId() {
    return registrationId;
  }


  @JsonProperty(REGISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegistrationId(String registrationId) {
    this.registrationId = registrationId;
  }

  public OAuthClientProperties clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

  /**
   * The client ID of the OAuth client used by the IDM
   * @return clientId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The client ID of the OAuth client used by the IDM")
  @JsonProperty(CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public OAuthClientProperties clientSecret(String clientSecret) {
    
    this.clientSecret = clientSecret;
    return this;
  }

  /**
   * The client secret of the OAuth client provided by the IDM
   * @return clientSecret
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The client secret of the OAuth client provided by the IDM")
  @JsonProperty(CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientSecret() {
    return clientSecret;
  }


  @JsonProperty(CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public OAuthClientProperties clientName(String clientName) {
    
    this.clientName = clientName;
    return this;
  }

  /**
   * Sets the logical name of the client or registration. Can be null
   * @return clientName
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Sets the logical name of the client or registration. Can be null")
  @JsonProperty(CLIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientName() {
    return clientName;
  }


  @JsonProperty(CLIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  public OAuthClientProperties authorizationUri(String authorizationUri) {
    
    this.authorizationUri = authorizationUri;
    return this;
  }

  /**
   * The authorization URI of the OAuth provider
   * @return authorizationUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The authorization URI of the OAuth provider")
  @JsonProperty(AUTHORIZATION_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthorizationUri() {
    return authorizationUri;
  }


  @JsonProperty(AUTHORIZATION_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorizationUri(String authorizationUri) {
    this.authorizationUri = authorizationUri;
  }

  public OAuthClientProperties tokenUri(String tokenUri) {
    
    this.tokenUri = tokenUri;
    return this;
  }

  /**
   * The token URI of the OAuth provider
   * @return tokenUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The token URI of the OAuth provider")
  @JsonProperty(TOKEN_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTokenUri() {
    return tokenUri;
  }


  @JsonProperty(TOKEN_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenUri(String tokenUri) {
    this.tokenUri = tokenUri;
  }

  public OAuthClientProperties userInfoUri(String userInfoUri) {
    
    this.userInfoUri = userInfoUri;
    return this;
  }

  /**
   * The user info URI of the OAuth provider
   * @return userInfoUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The user info URI of the OAuth provider")
  @JsonProperty(USER_INFO_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserInfoUri() {
    return userInfoUri;
  }


  @JsonProperty(USER_INFO_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserInfoUri(String userInfoUri) {
    this.userInfoUri = userInfoUri;
  }

  public OAuthClientProperties jwkSetUri(String jwkSetUri) {
    
    this.jwkSetUri = jwkSetUri;
    return this;
  }

  /**
   * The jwk set URI of the OAuth provider
   * @return jwkSetUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The jwk set URI of the OAuth provider")
  @JsonProperty(JWK_SET_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJwkSetUri() {
    return jwkSetUri;
  }


  @JsonProperty(JWK_SET_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJwkSetUri(String jwkSetUri) {
    this.jwkSetUri = jwkSetUri;
  }

  public OAuthClientProperties issuerUri(String issuerUri) {
    
    this.issuerUri = issuerUri;
    return this;
  }

  /**
   * \&quot;URI that can either be an OpenID Connect discovery endpoint or an OAuth 2.0  Authorization Server Metadata endpoint defined by RFC 8414.\&quot; 
   * @return issuerUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"URI that can either be an OpenID Connect discovery endpoint or an OAuth 2.0  Authorization Server Metadata endpoint defined by RFC 8414.\" ")
  @JsonProperty(ISSUER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerUri() {
    return issuerUri;
  }


  @JsonProperty(ISSUER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerUri(String issuerUri) {
    this.issuerUri = issuerUri;
  }

  public OAuthClientProperties redirectUri(String redirectUri) {
    
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * The redirect URI for the OAuth client
   * @return redirectUri
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The redirect URI for the OAuth client")
  @JsonProperty(REDIRECT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(REDIRECT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public OAuthClientProperties scope(String scope) {
    
    this.scope = scope;
    return this;
  }

  /**
   * The scope of the OAuth client, comma-separated
   * @return scope
   */
  @jakarta.annotation.Nullable

  @Schema(example = "openid, profile, email, roles", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The scope of the OAuth client, comma-separated")
  @JsonProperty(SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }


  @JsonProperty(SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(String scope) {
    this.scope = scope;
  }

  public OAuthClientProperties authorizationGrantType(String authorizationGrantType) {
    
    this.authorizationGrantType = authorizationGrantType;
    return this;
  }

  /**
   * The authorization grant type of the OAuth client
   * @return authorizationGrantType
   */
  @jakarta.annotation.Nullable

  @Schema(example = "authorization_code", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The authorization grant type of the OAuth client")
  @JsonProperty(AUTHORIZATION_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthorizationGrantType() {
    return authorizationGrantType;
  }


  @JsonProperty(AUTHORIZATION_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorizationGrantType(String authorizationGrantType) {
    this.authorizationGrantType = authorizationGrantType;
  }

  public OAuthClientProperties userNameAttribute(String userNameAttribute) {
    
    this.userNameAttribute = userNameAttribute;
    return this;
  }

  /**
   * The attribute of the user that can be used to identify the username
   * @return userNameAttribute
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(example = "preferred_username", requiredMode = Schema.RequiredMode.REQUIRED, description = "The attribute of the user that can be used to identify the username")
  @JsonProperty(USER_NAME_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserNameAttribute() {
    return userNameAttribute;
  }


  @JsonProperty(USER_NAME_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserNameAttribute(String userNameAttribute) {
    this.userNameAttribute = userNameAttribute;
  }

  public OAuthClientProperties userInfoAuthenticationMethod(String userInfoAuthenticationMethod) {
    
    this.userInfoAuthenticationMethod = userInfoAuthenticationMethod;
    return this;
  }

  /**
   * \&quot;The authentication method used when sending bearer access tokens in resource requests   to resource servers. Possible values: header/form/query.\&quot; 
   * @return userInfoAuthenticationMethod
   */
  @jakarta.annotation.Nullable

  @Schema(example = "header", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"The authentication method used when sending bearer access tokens in resource requests   to resource servers. Possible values: header/form/query.\" ")
  @JsonProperty(USER_INFO_AUTHENTICATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserInfoAuthenticationMethod() {
    return userInfoAuthenticationMethod;
  }


  @JsonProperty(USER_INFO_AUTHENTICATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserInfoAuthenticationMethod(String userInfoAuthenticationMethod) {
    this.userInfoAuthenticationMethod = userInfoAuthenticationMethod;
  }

  public OAuthClientProperties commonProvider(String commonProvider) {
    
    this.commonProvider = commonProvider;
    return this;
  }

  /**
   * \&quot;It is possible to set this attribute to use one of the common providers without setting  all config fields. Possible common providers: facebook, google, github, okta.\&quot; 
   * @return commonProvider
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"It is possible to set this attribute to use one of the common providers without setting  all config fields. Possible common providers: facebook, google, github, okta.\" ")
  @JsonProperty(COMMON_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommonProvider() {
    return commonProvider;
  }


  @JsonProperty(COMMON_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommonProvider(String commonProvider) {
    this.commonProvider = commonProvider;
  }

  public OAuthClientProperties logoutOidcEnabled(Boolean logoutOidcEnabled) {
    
    this.logoutOidcEnabled = logoutOidcEnabled;
    return this;
  }

  /**
   * With this field the oidc logout can be enabled.
   * @return logoutOidcEnabled
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "With this field the oidc logout can be enabled.")
  @JsonProperty(LOGOUT_OIDC_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLogoutOidcEnabled() {
    return logoutOidcEnabled;
  }


  @JsonProperty(LOGOUT_OIDC_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoutOidcEnabled(Boolean logoutOidcEnabled) {
    this.logoutOidcEnabled = logoutOidcEnabled;
  }

  public OAuthClientProperties logoutEndSessionEndpoint(String logoutEndSessionEndpoint) {
    
    this.logoutEndSessionEndpoint = logoutEndSessionEndpoint;
    return this;
  }

  /**
   * \&quot;When auto discovery of oidc endoints is not active (issuerUri is not set),  then this field can be used to explicitly configure the logout url\&quot; 
   * @return logoutEndSessionEndpoint
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"When auto discovery of oidc endoints is not active (issuerUri is not set),  then this field can be used to explicitly configure the logout url\" ")
  @JsonProperty(LOGOUT_END_SESSION_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoutEndSessionEndpoint() {
    return logoutEndSessionEndpoint;
  }


  @JsonProperty(LOGOUT_END_SESSION_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoutEndSessionEndpoint(String logoutEndSessionEndpoint) {
    this.logoutEndSessionEndpoint = logoutEndSessionEndpoint;
  }

  public OAuthClientProperties logoutRedirectPath(String logoutRedirectPath) {
    
    this.logoutRedirectPath = logoutRedirectPath;
    return this;
  }

  /**
   * \&quot;The redirect path that the IDM can redirect to after logout. {baseUrl} can be used.\&quot; 
   * @return logoutRedirectPath
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"The redirect path that the IDM can redirect to after logout. {baseUrl} can be used.\" ")
  @JsonProperty(LOGOUT_REDIRECT_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoutRedirectPath() {
    return logoutRedirectPath;
  }


  @JsonProperty(LOGOUT_REDIRECT_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoutRedirectPath(String logoutRedirectPath) {
    this.logoutRedirectPath = logoutRedirectPath;
  }

  public OAuthClientProperties label(String label) {
    
    this.label = label;
    return this;
  }

  /**
   * The text that can be used on ui
   * @return label
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The text that can be used on ui")
  @JsonProperty(LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(String label) {
    this.label = label;
  }

  public OAuthClientProperties logo(String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * The logo that can be used on ui. TBD
   * @return logo
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The logo that can be used on ui. TBD")
  @JsonProperty(LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogo(String logo) {
    this.logo = logo;
  }

  public OAuthClientProperties userParameterMapping(Map<String, String> userParameterMapping) {
    
    this.userParameterMapping = userParameterMapping;
    return this;
  }

  public OAuthClientProperties putUserParameterMappingItem(String key, String userParameterMappingItem) {
    if (this.userParameterMapping == null) {
      this.userParameterMapping = new HashMap<>();
    }
    this.userParameterMapping.put(key, userParameterMappingItem);
    return this;
  }

  /**
   * \&quot;This mapping contains the user attribute names stored in the application and the  corresponding attributes stored in the oauth realm. The key is the application, the  value is the realm attribute name.\&quot; 
   * @return userParameterMapping
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"This mapping contains the user attribute names stored in the application and the  corresponding attributes stored in the oauth realm. The key is the application, the  value is the realm attribute name.\" ")
  @JsonProperty(USER_PARAMETER_MAPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getUserParameterMapping() {
    return userParameterMapping;
  }


  @JsonProperty(USER_PARAMETER_MAPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserParameterMapping(Map<String, String> userParameterMapping) {
    this.userParameterMapping = userParameterMapping;
  }

  public OAuthClientProperties isUserWithoutGroupAllowedToLogIn(Boolean isUserWithoutGroupAllowedToLogIn) {
    
    this.isUserWithoutGroupAllowedToLogIn = isUserWithoutGroupAllowedToLogIn;
    return this;
  }

  /**
   * \&quot;When true, users without groups can not log in into the application.\&quot; 
   * @return isUserWithoutGroupAllowedToLogIn
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"When true, users without groups can not log in into the application.\" ")
  @JsonProperty(IS_USER_WITHOUT_GROUP_ALLOWED_TO_LOG_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsUserWithoutGroupAllowedToLogIn() {
    return isUserWithoutGroupAllowedToLogIn;
  }


  @JsonProperty(IS_USER_WITHOUT_GROUP_ALLOWED_TO_LOG_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsUserWithoutGroupAllowedToLogIn(Boolean isUserWithoutGroupAllowedToLogIn) {
    this.isUserWithoutGroupAllowedToLogIn = isUserWithoutGroupAllowedToLogIn;
  }

  public OAuthClientProperties defaultGroupName(String defaultGroupName) {
    
    this.defaultGroupName = defaultGroupName;
    return this;
  }

  /**
   * \&quot;The name of the SecurityGroup that the logged in user is added to as default.\&quot; 
   * @return defaultGroupName
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"The name of the SecurityGroup that the logged in user is added to as default.\" ")
  @JsonProperty(DEFAULT_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultGroupName() {
    return defaultGroupName;
  }


  @JsonProperty(DEFAULT_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultGroupName(String defaultGroupName) {
    this.defaultGroupName = defaultGroupName;
  }

  public OAuthClientProperties roleAttributes(List<String> roleAttributes) {
    
    this.roleAttributes = roleAttributes;
    return this;
  }

  public OAuthClientProperties addRoleAttributesItem(String roleAttributesItem) {
    if (this.roleAttributes == null) {
      this.roleAttributes = new ArrayList<>();
    }
    this.roleAttributes.add(roleAttributesItem);
    return this;
  }

  /**
   * \&quot;The attributes sent by the identity provider holding the lists of the role names.\&quot; 
   * @return roleAttributes
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"The attributes sent by the identity provider holding the lists of the role names.\" ")
  @JsonProperty(ROLE_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRoleAttributes() {
    return roleAttributes;
  }


  @JsonProperty(ROLE_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleAttributes(List<String> roleAttributes) {
    this.roleAttributes = roleAttributes;
  }

  public OAuthClientProperties roleMapping(Map<String, String> roleMapping) {
    
    this.roleMapping = roleMapping;
    return this;
  }

  public OAuthClientProperties putRoleMappingItem(String key, String roleMappingItem) {
    if (this.roleMapping == null) {
      this.roleMapping = new HashMap<>();
    }
    this.roleMapping.put(key, roleMappingItem);
    return this;
  }

  /**
   * \&quot;This mapping contains the users&#39; role names stored in the oauth realm and the  corresponding group names stored in the application . The key is the realm role name,  the value is the application group name.\&quot; 
   * @return roleMapping
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"This mapping contains the users' role names stored in the oauth realm and the  corresponding group names stored in the application . The key is the realm role name,  the value is the application group name.\" ")
  @JsonProperty(ROLE_MAPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getRoleMapping() {
    return roleMapping;
  }


  @JsonProperty(ROLE_MAPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleMapping(Map<String, String> roleMapping) {
    this.roleMapping = roleMapping;
  }

  public OAuthClientProperties clientAuthenticationMethod(String clientAuthenticationMethod) {
    
    this.clientAuthenticationMethod = clientAuthenticationMethod;
    return this;
  }

  /**
   * Get clientAuthenticationMethod
   * @return clientAuthenticationMethod
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(CLIENT_AUTHENTICATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientAuthenticationMethod() {
    return clientAuthenticationMethod;
  }


  @JsonProperty(CLIENT_AUTHENTICATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientAuthenticationMethod(String clientAuthenticationMethod) {
    this.clientAuthenticationMethod = clientAuthenticationMethod;
  }

  public OAuthClientProperties isPkceEnabled(Boolean isPkceEnabled) {
    
    this.isPkceEnabled = isPkceEnabled;
    return this;
  }

  /**
   * \&quot;Enabeles PKCE so it adds PKCE parameters to authorization request\&quot;
   * @return isPkceEnabled
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "\"Enabeles PKCE so it adds PKCE parameters to authorization request\"")
  @JsonProperty(IS_PKCE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPkceEnabled() {
    return isPkceEnabled;
  }


  @JsonProperty(IS_PKCE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPkceEnabled(Boolean isPkceEnabled) {
    this.isPkceEnabled = isPkceEnabled;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthClientProperties oauthClientProperties = (OAuthClientProperties) o;
    return Objects.equals(this.uri, oauthClientProperties.uri) &&
        Objects.equals(this.registrationId, oauthClientProperties.registrationId) &&
        Objects.equals(this.clientId, oauthClientProperties.clientId) &&
        Objects.equals(this.clientSecret, oauthClientProperties.clientSecret) &&
        Objects.equals(this.clientName, oauthClientProperties.clientName) &&
        Objects.equals(this.authorizationUri, oauthClientProperties.authorizationUri) &&
        Objects.equals(this.tokenUri, oauthClientProperties.tokenUri) &&
        Objects.equals(this.userInfoUri, oauthClientProperties.userInfoUri) &&
        Objects.equals(this.jwkSetUri, oauthClientProperties.jwkSetUri) &&
        Objects.equals(this.issuerUri, oauthClientProperties.issuerUri) &&
        Objects.equals(this.redirectUri, oauthClientProperties.redirectUri) &&
        Objects.equals(this.scope, oauthClientProperties.scope) &&
        Objects.equals(this.authorizationGrantType, oauthClientProperties.authorizationGrantType) &&
        Objects.equals(this.userNameAttribute, oauthClientProperties.userNameAttribute) &&
        Objects.equals(this.userInfoAuthenticationMethod, oauthClientProperties.userInfoAuthenticationMethod) &&
        Objects.equals(this.commonProvider, oauthClientProperties.commonProvider) &&
        Objects.equals(this.logoutOidcEnabled, oauthClientProperties.logoutOidcEnabled) &&
        Objects.equals(this.logoutEndSessionEndpoint, oauthClientProperties.logoutEndSessionEndpoint) &&
        Objects.equals(this.logoutRedirectPath, oauthClientProperties.logoutRedirectPath) &&
        Objects.equals(this.label, oauthClientProperties.label) &&
        Objects.equals(this.logo, oauthClientProperties.logo) &&
        Objects.equals(this.userParameterMapping, oauthClientProperties.userParameterMapping) &&
        Objects.equals(this.isUserWithoutGroupAllowedToLogIn, oauthClientProperties.isUserWithoutGroupAllowedToLogIn) &&
        Objects.equals(this.defaultGroupName, oauthClientProperties.defaultGroupName) &&
        Objects.equals(this.roleAttributes, oauthClientProperties.roleAttributes) &&
        Objects.equals(this.roleMapping, oauthClientProperties.roleMapping) &&
        Objects.equals(this.clientAuthenticationMethod, oauthClientProperties.clientAuthenticationMethod) &&
        Objects.equals(this.isPkceEnabled, oauthClientProperties.isPkceEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, registrationId, clientId, clientSecret, clientName, authorizationUri, tokenUri, userInfoUri, jwkSetUri, issuerUri, redirectUri, scope, authorizationGrantType, userNameAttribute, userInfoAuthenticationMethod, commonProvider, logoutOidcEnabled, logoutEndSessionEndpoint, logoutRedirectPath, label, logo, userParameterMapping, isUserWithoutGroupAllowedToLogIn, defaultGroupName, roleAttributes, roleMapping, clientAuthenticationMethod, isPkceEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthClientProperties {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    registrationId: ").append(toIndentedString(registrationId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    authorizationUri: ").append(toIndentedString(authorizationUri)).append("\n");
    sb.append("    tokenUri: ").append(toIndentedString(tokenUri)).append("\n");
    sb.append("    userInfoUri: ").append(toIndentedString(userInfoUri)).append("\n");
    sb.append("    jwkSetUri: ").append(toIndentedString(jwkSetUri)).append("\n");
    sb.append("    issuerUri: ").append(toIndentedString(issuerUri)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    authorizationGrantType: ").append(toIndentedString(authorizationGrantType)).append("\n");
    sb.append("    userNameAttribute: ").append(toIndentedString(userNameAttribute)).append("\n");
    sb.append("    userInfoAuthenticationMethod: ").append(toIndentedString(userInfoAuthenticationMethod)).append("\n");
    sb.append("    commonProvider: ").append(toIndentedString(commonProvider)).append("\n");
    sb.append("    logoutOidcEnabled: ").append(toIndentedString(logoutOidcEnabled)).append("\n");
    sb.append("    logoutEndSessionEndpoint: ").append(toIndentedString(logoutEndSessionEndpoint)).append("\n");
    sb.append("    logoutRedirectPath: ").append(toIndentedString(logoutRedirectPath)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    userParameterMapping: ").append(toIndentedString(userParameterMapping)).append("\n");
    sb.append("    isUserWithoutGroupAllowedToLogIn: ").append(toIndentedString(isUserWithoutGroupAllowedToLogIn)).append("\n");
    sb.append("    defaultGroupName: ").append(toIndentedString(defaultGroupName)).append("\n");
    sb.append("    roleAttributes: ").append(toIndentedString(roleAttributes)).append("\n");
    sb.append("    roleMapping: ").append(toIndentedString(roleMapping)).append("\n");
    sb.append("    clientAuthenticationMethod: ").append(toIndentedString(clientAuthenticationMethod)).append("\n");
    sb.append("    isPkceEnabled: ").append(toIndentedString(isPkceEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

