/*
 * Filter API 2
 * Filter API 2
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.filterexpression.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.filterexpression.bean.SearchConfigHierarchyFilter;
import org.smartbit4all.api.filterexpression.bean.SearchPageConfig;
import org.smartbit4all.api.view.bean.UiActionDescriptor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This object has every configuration data that is necessary to open a SearchIndexResult page. It contains the possible filter expressions in a FilterExpresisonBuilderModel and also the parameterization of the result grid in a GridViewDescriptor object. 
 */
@ApiModel(description = "This object has every configuration data that is necessary to open a SearchIndexResult page. It contains the possible filter expressions in a FilterExpresisonBuilderModel and also the parameterization of the result grid in a GridViewDescriptor object. ")
@JsonPropertyOrder({
  SearchConfigHierarchy.URI,
  SearchConfigHierarchy.CODE,
  SearchConfigHierarchy.SEARCH_CONFIG,
  SearchConfigHierarchy.FILTERS,
  SearchConfigHierarchy.ACTION_DESCRIPTOR
})
@JsonTypeName("SearchConfigHierarchy")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SearchConfigHierarchy {
  public static final String URI = "uri";
  private URI uri;

  public static final String CODE = "code";
  private String code;

  public static final String SEARCH_CONFIG = "searchConfig";
  private SearchPageConfig searchConfig;

  public static final String FILTERS = "filters";
  private List<SearchConfigHierarchyFilter> filters = new ArrayList<>();

  public static final String ACTION_DESCRIPTOR = "actionDescriptor";
  private UiActionDescriptor actionDescriptor = null;

  public SearchConfigHierarchy() { 
  }

  public SearchConfigHierarchy uri(URI uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUri() {
    return uri;
  }


  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(URI uri) {
    this.uri = uri;
  }


  public SearchConfigHierarchy code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public SearchConfigHierarchy searchConfig(SearchPageConfig searchConfig) {
    
    this.searchConfig = searchConfig;
    return this;
  }

   /**
   * Get searchConfig
   * @return searchConfig
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(SEARCH_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SearchPageConfig getSearchConfig() {
    return searchConfig;
  }


  @JsonProperty(SEARCH_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchConfig(SearchPageConfig searchConfig) {
    this.searchConfig = searchConfig;
  }


  public SearchConfigHierarchy filters(List<SearchConfigHierarchyFilter> filters) {
    
    this.filters = filters;
    return this;
  }

  public SearchConfigHierarchy addFiltersItem(SearchConfigHierarchyFilter filtersItem) {
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(FILTERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SearchConfigHierarchyFilter> getFilters() {
    return filters;
  }


  @JsonProperty(FILTERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilters(List<SearchConfigHierarchyFilter> filters) {
    this.filters = filters;
  }


  public SearchConfigHierarchy actionDescriptor(UiActionDescriptor actionDescriptor) {
    
    this.actionDescriptor = actionDescriptor;
    return this;
  }

   /**
   * Get actionDescriptor
   * @return actionDescriptor
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(ACTION_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UiActionDescriptor getActionDescriptor() {
    return actionDescriptor;
  }


  @JsonProperty(ACTION_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionDescriptor(UiActionDescriptor actionDescriptor) {
    this.actionDescriptor = actionDescriptor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchConfigHierarchy searchConfigHierarchy = (SearchConfigHierarchy) o;
    return Objects.equals(this.uri, searchConfigHierarchy.uri) &&
        Objects.equals(this.code, searchConfigHierarchy.code) &&
        Objects.equals(this.searchConfig, searchConfigHierarchy.searchConfig) &&
        Objects.equals(this.filters, searchConfigHierarchy.filters) &&
        Objects.equals(this.actionDescriptor, searchConfigHierarchy.actionDescriptor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, code, searchConfig, filters, actionDescriptor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchConfigHierarchy {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    searchConfig: ").append(toIndentedString(searchConfig)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    actionDescriptor: ").append(toIndentedString(actionDescriptor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

