/*
 * diagram API
 * Describes a model for a diagram.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.diagram.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * DiagramColor
 */
@JsonPropertyOrder({
  DiagramColor.RED,
  DiagramColor.GREEN,
  DiagramColor.BLUE,
  DiagramColor.ALPHA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class DiagramColor {
  public static final String RED = "red";
  private Integer red;

  public static final String GREEN = "green";
  private Integer green;

  public static final String BLUE = "blue";
  private Integer blue;

  public static final String ALPHA = "alpha";
  private Float alpha;

  public DiagramColor() {
  }

  public DiagramColor red(Integer red) {
    
    this.red = red;
    return this;
  }

  /**
   * Get red
   * @return red
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(RED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRed() {
    return red;
  }


  @JsonProperty(RED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRed(Integer red) {
    this.red = red;
  }

  public DiagramColor green(Integer green) {
    
    this.green = green;
    return this;
  }

  /**
   * Get green
   * @return green
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(GREEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getGreen() {
    return green;
  }


  @JsonProperty(GREEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGreen(Integer green) {
    this.green = green;
  }

  public DiagramColor blue(Integer blue) {
    
    this.blue = blue;
    return this;
  }

  /**
   * Get blue
   * @return blue
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(BLUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBlue() {
    return blue;
  }


  @JsonProperty(BLUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlue(Integer blue) {
    this.blue = blue;
  }

  public DiagramColor alpha(Float alpha) {
    
    this.alpha = alpha;
    return this;
  }

  /**
   * Get alpha
   * @return alpha
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(ALPHA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAlpha() {
    return alpha;
  }


  @JsonProperty(ALPHA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlpha(Float alpha) {
    this.alpha = alpha;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagramColor diagramColor = (DiagramColor) o;
    return Objects.equals(this.red, diagramColor.red) &&
        Objects.equals(this.green, diagramColor.green) &&
        Objects.equals(this.blue, diagramColor.blue) &&
        Objects.equals(this.alpha, diagramColor.alpha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(red, green, blue, alpha);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagramColor {\n");
    sb.append("    red: ").append(toIndentedString(red)).append("\n");
    sb.append("    green: ").append(toIndentedString(green)).append("\n");
    sb.append("    blue: ").append(toIndentedString(blue)).append("\n");
    sb.append("    alpha: ").append(toIndentedString(alpha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

