/*
 * storage api
 * The storage api is a generic possibility to store and load objects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.storage.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.storage.bean.ObjectHistoryEntry;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ObjectHistory
 */
@JsonPropertyOrder({
  ObjectHistory.TITLE,
  ObjectHistory.OBJECT_HISTORY_ENTRIES
})
@JsonTypeName("ObjectHistory")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ObjectHistory {
  public static final String TITLE = "title";
  private String title;

  public static final String OBJECT_HISTORY_ENTRIES = "objectHistoryEntries";
  private List<ObjectHistoryEntry> objectHistoryEntries = null;


  public ObjectHistory title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public ObjectHistory objectHistoryEntries(List<ObjectHistoryEntry> objectHistoryEntries) {
    
    this.objectHistoryEntries = objectHistoryEntries;
    return this;
  }

  public ObjectHistory addObjectHistoryEntriesItem(ObjectHistoryEntry objectHistoryEntriesItem) {
    if (this.objectHistoryEntries == null) {
      this.objectHistoryEntries = new ArrayList<>();
    }
    this.objectHistoryEntries.add(objectHistoryEntriesItem);
    return this;
  }

   /**
   * Get objectHistoryEntries
   * @return objectHistoryEntries
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(OBJECT_HISTORY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ObjectHistoryEntry> getObjectHistoryEntries() {
    return objectHistoryEntries;
  }


  @JsonProperty(OBJECT_HISTORY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectHistoryEntries(List<ObjectHistoryEntry> objectHistoryEntries) {
    this.objectHistoryEntries = objectHistoryEntries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectHistory objectHistory = (ObjectHistory) o;
    return Objects.equals(this.title, objectHistory.title) &&
        Objects.equals(this.objectHistoryEntries, objectHistory.objectHistoryEntries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, objectHistoryEntries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectHistory {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    objectHistoryEntries: ").append(toIndentedString(objectHistoryEntries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

