/*
 * storage api
 * The storage api is a generic possibility to store and load objects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.storage.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.storage.bean.ObjectReference;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The list of references as a container object for the Api.  
 */
@ApiModel(description = "The list of references as a container object for the Api.  ")
@JsonPropertyOrder({
  ObjectReferenceList.REFERENCE_TYPE_CLASS,
  ObjectReferenceList.REFERENCES
})
@JsonTypeName("ObjectReferenceList")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ObjectReferenceList {
  public static final String REFERENCE_TYPE_CLASS = "referenceTypeClass";
  private String referenceTypeClass;

  public static final String REFERENCES = "references";
  private List<ObjectReference> references = new ArrayList<>();


  public ObjectReferenceList referenceTypeClass(String referenceTypeClass) {
    
    this.referenceTypeClass = referenceTypeClass;
    return this;
  }

   /**
   * The type of the reference. It can be the qualified name of the java bean class or anything else that can exactly identify the type of the reference object.   
   * @return referenceTypeClass
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "The type of the reference. It can be the qualified name of the java bean class or anything else that can exactly identify the type of the reference object.   ")
  @JsonProperty(REFERENCE_TYPE_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReferenceTypeClass() {
    return referenceTypeClass;
  }


  @JsonProperty(REFERENCE_TYPE_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferenceTypeClass(String referenceTypeClass) {
    this.referenceTypeClass = referenceTypeClass;
  }


  public ObjectReferenceList references(List<ObjectReference> references) {
    
    this.references = references;
    return this;
  }

  public ObjectReferenceList addReferencesItem(ObjectReference referencesItem) {
    this.references.add(referencesItem);
    return this;
  }

   /**
   * Get references
   * @return references
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(REFERENCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ObjectReference> getReferences() {
    return references;
  }


  @JsonProperty(REFERENCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferences(List<ObjectReference> references) {
    this.references = references;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectReferenceList objectReferenceList = (ObjectReferenceList) o;
    return Objects.equals(this.referenceTypeClass, objectReferenceList.referenceTypeClass) &&
        Objects.equals(this.references, objectReferenceList.references);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceTypeClass, references);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectReferenceList {\n");
    sb.append("    referenceTypeClass: ").append(toIndentedString(referenceTypeClass)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

