/*
 * Attachment grid api
 * Attachment grid api.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.bff.api.attachmentgrid.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.smartbit4all.api.invocation.bean.InvocationRequest;
import org.smartbit4all.api.view.bean.UiActionDescriptor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Describes an additional action, for the attachment grid.
 */
@Schema(description = "Describes an additional action, for the attachment grid.")
@JsonPropertyOrder({
  AdditionalAttachmentAction.CODE,
  AdditionalAttachmentAction.DESCRIPTOR,
  AdditionalAttachmentAction.ACTION_INVOCATION_REQUEST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class AdditionalAttachmentAction {
  public static final String CODE = "code";
  private String code;

  public static final String DESCRIPTOR = "descriptor";
  private UiActionDescriptor descriptor = null;

  public static final String ACTION_INVOCATION_REQUEST = "actionInvocationRequest";
  private InvocationRequest actionInvocationRequest = null;

  public AdditionalAttachmentAction() {
  }

  public AdditionalAttachmentAction code(String code) {
    
    this.code = code;
    return this;
  }

  /**
   * The title of the action.
   * @return code
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The title of the action.")
  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }

  public AdditionalAttachmentAction descriptor(UiActionDescriptor descriptor) {
    
    this.descriptor = descriptor;
    return this;
  }

  /**
   * Get descriptor
   * @return descriptor
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UiActionDescriptor getDescriptor() {
    return descriptor;
  }


  @JsonProperty(DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptor(UiActionDescriptor descriptor) {
    this.descriptor = descriptor;
  }

  public AdditionalAttachmentAction actionInvocationRequest(InvocationRequest actionInvocationRequest) {
    
    this.actionInvocationRequest = actionInvocationRequest;
    return this;
  }

  /**
   * The additional action itself
   * @return actionInvocationRequest
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The additional action itself")
  @JsonProperty(ACTION_INVOCATION_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvocationRequest getActionInvocationRequest() {
    return actionInvocationRequest;
  }


  @JsonProperty(ACTION_INVOCATION_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionInvocationRequest(InvocationRequest actionInvocationRequest) {
    this.actionInvocationRequest = actionInvocationRequest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalAttachmentAction additionalAttachmentAction = (AdditionalAttachmentAction) o;
    return Objects.equals(this.code, additionalAttachmentAction.code) &&
        Objects.equals(this.descriptor, additionalAttachmentAction.descriptor) &&
        Objects.equals(this.actionInvocationRequest, additionalAttachmentAction.actionInvocationRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, descriptor, actionInvocationRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalAttachmentAction {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    actionInvocationRequest: ").append(toIndentedString(actionInvocationRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

