/*
 * Attachment grid api
 * Attachment grid api.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.bff.api.attachmentgrid.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.smartbit4all.api.attachment.bean.BinaryContentData;
import org.smartbit4all.api.invocation.bean.InvocationRequest;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Describes an attachment grid, made up of BinaryContentDatas.
 */
@ApiModel(description = "Describes an attachment grid, made up of BinaryContentDatas.")
@JsonPropertyOrder({
  AttachmentGridDescriptor.ATTACHMENT_LIST,
  AttachmentGridDescriptor.GRID_WIDGET_ID,
  AttachmentGridDescriptor.VIEW_UUID,
  AttachmentGridDescriptor.BUTTON_COLOR,
  AttachmentGridDescriptor.LOGICAL_SCHEMA,
  AttachmentGridDescriptor.SAVE_REQUEST,
  AttachmentGridDescriptor.IS_PREVIEWABLE,
  AttachmentGridDescriptor.IS_DOWNLOADABLE,
  AttachmentGridDescriptor.IS_EDITABLE,
  AttachmentGridDescriptor.IS_PAGINATOR_ENABLED,
  AttachmentGridDescriptor.PAGE_SIZE
})
@JsonTypeName("AttachmentGridDescriptor")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AttachmentGridDescriptor {
  public static final String ATTACHMENT_LIST = "attachmentList";
  private List<BinaryContentData> attachmentList = null;

  public static final String GRID_WIDGET_ID = "gridWidgetId";
  private String gridWidgetId;

  public static final String VIEW_UUID = "viewUuid";
  private UUID viewUuid;

  public static final String BUTTON_COLOR = "buttonColor";
  private String buttonColor = "primary";

  public static final String LOGICAL_SCHEMA = "logicalSchema";
  private String logicalSchema;

  public static final String SAVE_REQUEST = "saveRequest";
  private InvocationRequest saveRequest = null;

  public static final String IS_PREVIEWABLE = "isPreviewable";
  private Boolean isPreviewable = true;

  public static final String IS_DOWNLOADABLE = "isDownloadable";
  private Boolean isDownloadable = true;

  public static final String IS_EDITABLE = "isEditable";
  private Boolean isEditable = false;

  public static final String IS_PAGINATOR_ENABLED = "isPaginatorEnabled";
  private Boolean isPaginatorEnabled = true;

  public static final String PAGE_SIZE = "pageSize";
  private Integer pageSize;

  public AttachmentGridDescriptor() { 
  }

  public AttachmentGridDescriptor attachmentList(List<BinaryContentData> attachmentList) {
    
    this.attachmentList = attachmentList;
    return this;
  }

  public AttachmentGridDescriptor addAttachmentListItem(BinaryContentData attachmentListItem) {
    if (this.attachmentList == null) {
      this.attachmentList = new ArrayList<>();
    }
    this.attachmentList.add(attachmentListItem);
    return this;
  }

   /**
   * Get attachmentList
   * @return attachmentList
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(ATTACHMENT_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BinaryContentData> getAttachmentList() {
    return attachmentList;
  }


  @JsonProperty(ATTACHMENT_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachmentList(List<BinaryContentData> attachmentList) {
    this.attachmentList = attachmentList;
  }


  public AttachmentGridDescriptor gridWidgetId(String gridWidgetId) {
    
    this.gridWidgetId = gridWidgetId;
    return this;
  }

   /**
   * Get gridWidgetId
   * @return gridWidgetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(GRID_WIDGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGridWidgetId() {
    return gridWidgetId;
  }


  @JsonProperty(GRID_WIDGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGridWidgetId(String gridWidgetId) {
    this.gridWidgetId = gridWidgetId;
  }


  public AttachmentGridDescriptor viewUuid(UUID viewUuid) {
    
    this.viewUuid = viewUuid;
    return this;
  }

   /**
   * Get viewUuid
   * @return viewUuid
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(VIEW_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getViewUuid() {
    return viewUuid;
  }


  @JsonProperty(VIEW_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewUuid(UUID viewUuid) {
    this.viewUuid = viewUuid;
  }


  public AttachmentGridDescriptor buttonColor(String buttonColor) {
    
    this.buttonColor = buttonColor;
    return this;
  }

   /**
   * Get buttonColor
   * @return buttonColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(BUTTON_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getButtonColor() {
    return buttonColor;
  }


  @JsonProperty(BUTTON_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setButtonColor(String buttonColor) {
    this.buttonColor = buttonColor;
  }


  public AttachmentGridDescriptor logicalSchema(String logicalSchema) {
    
    this.logicalSchema = logicalSchema;
    return this;
  }

   /**
   * Get logicalSchema
   * @return logicalSchema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(LOGICAL_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogicalSchema() {
    return logicalSchema;
  }


  @JsonProperty(LOGICAL_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogicalSchema(String logicalSchema) {
    this.logicalSchema = logicalSchema;
  }


  public AttachmentGridDescriptor saveRequest(InvocationRequest saveRequest) {
    
    this.saveRequest = saveRequest;
    return this;
  }

   /**
   * Get saveRequest
   * @return saveRequest
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(SAVE_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvocationRequest getSaveRequest() {
    return saveRequest;
  }


  @JsonProperty(SAVE_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaveRequest(InvocationRequest saveRequest) {
    this.saveRequest = saveRequest;
  }


  public AttachmentGridDescriptor isPreviewable(Boolean isPreviewable) {
    
    this.isPreviewable = isPreviewable;
    return this;
  }

   /**
   * Get isPreviewable
   * @return isPreviewable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(IS_PREVIEWABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPreviewable() {
    return isPreviewable;
  }


  @JsonProperty(IS_PREVIEWABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPreviewable(Boolean isPreviewable) {
    this.isPreviewable = isPreviewable;
  }


  public AttachmentGridDescriptor isDownloadable(Boolean isDownloadable) {
    
    this.isDownloadable = isDownloadable;
    return this;
  }

   /**
   * Get isDownloadable
   * @return isDownloadable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(IS_DOWNLOADABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDownloadable() {
    return isDownloadable;
  }


  @JsonProperty(IS_DOWNLOADABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDownloadable(Boolean isDownloadable) {
    this.isDownloadable = isDownloadable;
  }


  public AttachmentGridDescriptor isEditable(Boolean isEditable) {
    
    this.isEditable = isEditable;
    return this;
  }

   /**
   * Get isEditable
   * @return isEditable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(IS_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsEditable() {
    return isEditable;
  }


  @JsonProperty(IS_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEditable(Boolean isEditable) {
    this.isEditable = isEditable;
  }


  public AttachmentGridDescriptor isPaginatorEnabled(Boolean isPaginatorEnabled) {
    
    this.isPaginatorEnabled = isPaginatorEnabled;
    return this;
  }

   /**
   * Get isPaginatorEnabled
   * @return isPaginatorEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(IS_PAGINATOR_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPaginatorEnabled() {
    return isPaginatorEnabled;
  }


  @JsonProperty(IS_PAGINATOR_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPaginatorEnabled(Boolean isPaginatorEnabled) {
    this.isPaginatorEnabled = isPaginatorEnabled;
  }


  public AttachmentGridDescriptor pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentGridDescriptor attachmentGridDescriptor = (AttachmentGridDescriptor) o;
    return Objects.equals(this.attachmentList, attachmentGridDescriptor.attachmentList) &&
        Objects.equals(this.gridWidgetId, attachmentGridDescriptor.gridWidgetId) &&
        Objects.equals(this.viewUuid, attachmentGridDescriptor.viewUuid) &&
        Objects.equals(this.buttonColor, attachmentGridDescriptor.buttonColor) &&
        Objects.equals(this.logicalSchema, attachmentGridDescriptor.logicalSchema) &&
        Objects.equals(this.saveRequest, attachmentGridDescriptor.saveRequest) &&
        Objects.equals(this.isPreviewable, attachmentGridDescriptor.isPreviewable) &&
        Objects.equals(this.isDownloadable, attachmentGridDescriptor.isDownloadable) &&
        Objects.equals(this.isEditable, attachmentGridDescriptor.isEditable) &&
        Objects.equals(this.isPaginatorEnabled, attachmentGridDescriptor.isPaginatorEnabled) &&
        Objects.equals(this.pageSize, attachmentGridDescriptor.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachmentList, gridWidgetId, viewUuid, buttonColor, logicalSchema, saveRequest, isPreviewable, isDownloadable, isEditable, isPaginatorEnabled, pageSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentGridDescriptor {\n");
    sb.append("    attachmentList: ").append(toIndentedString(attachmentList)).append("\n");
    sb.append("    gridWidgetId: ").append(toIndentedString(gridWidgetId)).append("\n");
    sb.append("    viewUuid: ").append(toIndentedString(viewUuid)).append("\n");
    sb.append("    buttonColor: ").append(toIndentedString(buttonColor)).append("\n");
    sb.append("    logicalSchema: ").append(toIndentedString(logicalSchema)).append("\n");
    sb.append("    saveRequest: ").append(toIndentedString(saveRequest)).append("\n");
    sb.append("    isPreviewable: ").append(toIndentedString(isPreviewable)).append("\n");
    sb.append("    isDownloadable: ").append(toIndentedString(isDownloadable)).append("\n");
    sb.append("    isEditable: ").append(toIndentedString(isEditable)).append("\n");
    sb.append("    isPaginatorEnabled: ").append(toIndentedString(isPaginatorEnabled)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

