plugins {
  // id 'org.springframework.boot'
  // id 'io.spring.dependency-management'
}

dependencies {
  api project(':sec')
  api project(':api')

  implementation 'com.azure.spring:spring-cloud-azure-dependencies:5.16.0'
  implementation 'com.azure.spring:spring-cloud-azure-starter-active-directory:5.16.0'

  api 'org.springframework.security:spring-security-oauth2-client'
  api 'org.springframework.security:spring-security-oauth2-jose'

  implementation 'com.microsoft.graph:microsoft-graph:6.17.0'
  implementation 'com.azure:azure-identity:1.11.0'
}


//configurations {
//  [apiElements, runtimeElements].each {
//    it.outgoing.artifacts.removeIf { it.buildDependencies.getDependencies(null).contains(jar) }
//    it.outgoing.artifact(bootJar)
//  }
//}
