CREATE SEQUENCE SQL_TEST_EXISTS_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE Test (
  "KEY" VARCHAR2(255) NOT NULL,
  "STATE" VARCHAR2(255) NULL,
  "EMPTYSTATE" VARCHAR2(255) NULL,
  "ISACTIVE" VARCHAR2(255) NULL,
  "CONTENT" BLOB NULL
);
