/**
 * Tree domain objects
 * Tree domain objects
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TreeNodeKind = 'entry' | 'association' | 'reference';

export const TreeNodeKind = {
    Entry: 'entry' as TreeNodeKind,
    Association: 'association' as TreeNodeKind,
    Reference: 'reference' as TreeNodeKind
};

