# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

schedules:
- cron: "0 2 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: Gradle@2
  inputs:
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean test'
