rootProject.name = 'platform'

// includeBuild '../platform-gradle'

include 'api'
include 'api-domain'
include 'api-cli-rest'
include 'api-srv-rest'
include 'bff-api'
include 'bff-domain'
include 'sql'
include 'json'
include 'sec'
include 'invocation-cli-rest'
include 'invocation-srv-rest'
include 'content-access-srv-rest'
include 'testing'

def localSettings = file("local.settings.gradle")
if (localSettings.exists()) {
  apply from:localSettings
}
