openapi: 3.0.1
info:
  title: Grid UI API
  description: Grid UI API
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: grid
    description: grid
paths:
  /grid/{uuid}/{gridIdentifier}/load:
    post:
      tags:
      - grid
      summary: ''
      operationId: 'load'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: gridIdentifier
          schema:
            type: string
          required: true
          description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: GridModel
  /grid/{uuid}/{gridIdentifier}/page/{offset}/{limit}:
    post:
      tags:
      - grid
      summary: ''
      operationId: 'setPage'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: gridIdentifier
          schema:
            type: string
          required: true
          description: ''
        - in: path
          name: offset
          schema:
            type: string
          required: true
          description: ''
        - in: path
          name: limit
          schema:
            type: string
          required: true
          description: ''
      responses:
        '200':
          description: ''
  /grid/{uuid}/{gridIdentifier}/performAction/{actionIdentifier}:
    post:
      tags:
      - grid
      summary: ''
      operationId: 'performAction'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: gridIdentifier
          schema:
            type: string
          required: true
          description: ''
        - in: path
          name: actionIdentifier
          schema:
            type: string
          required: true
          description: ''
      responses:
        '200':
          description: 'OK'
        '404':
          description: 'NOK'