openapi: 3.0.1
info:
  title: Navigation API
  description: Navigation API
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: navigation
    description: navigation
paths:
  /createViewModel:
    post:
      tags:
      - view-model
      summary: ''
      operationId: 'createViewModel'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NavigationTarget'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewModelData'
  /setModel/{uuid}:
    post:
      tags:
      - view-model
      summary: ''
      operationId: 'setModel'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Object'
      responses:
        '200':
          description: ''
  /executeCommand/{uuid}:
    post:
      tags:
      - view-model
      summary: ''
      operationId: 'executeCommand'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandData'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
  /getModel/{uuid}:
    get:
      tags:
      - view-model
      summary: ''
      operationId: 'getModel'
      parameters: 
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewModelData'
  /upload:
    post:
      tags:
      - view-model
      summary: 'Executes a command similar to executeCommand, but appends a BinaryData to it params'
      operationId: 'upload'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                  format: uuid
                command:
                  $ref: '#/components/schemas/CommandData'
                content:
                  type: string
                  format: binary
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
  /download/{vmUuid}/{dataUuid}:
    get:
      tags:
      - view-model
      summary: ''
      operationId: 'download'
      parameters:
        - in: path
          name: vmUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: dataUuid
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: 'Data in given ViewModel (vmUuid) with the given dataUuid.'
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    AppState:
      type: object
      description:
      properties:
        uuid:
          type: string
          format: uuid
        uis:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UIState'
    UIState:
      type: object
      required:
        - uuid
        - views
      properties:
        uuid:
          type: string
          format: uuid
        uiToOpen:
          $ref: '#/components/schemas/NavigationTarget'
        messageToOpen:
          $ref: '#/components/schemas/Message'
        views:
          type: array
          items:
            $ref: '#/components/schemas/ViewModelData'
    ViewModelData:
      type: object
      description: Represent a viewmodel's data.
      required:
        - uuid
        - children
      properties:
        uuid:
          type: string
          format: uuid
        path:
          type: string
        navigationTarget:
          $ref: '#/components/schemas/NavigationTarget'
        model:
          $ref: '#/components/schemas/Object'
        children:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ViewModelDataSimple'
    ViewModelDataSimple:
      type: object
      description: Represent a viewmodel's data.
      required:
        - uuid
        - children
      properties:
        uuid:
          type: string
          format: uuid
        path:
          type: string
        navigationTarget:
          $ref: '#/components/schemas/NavigationTarget'
        children:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ViewModelDataSimple'
    NavigationTarget:
      type: object
      required:
        - uuid
        - viewName
        - state
        - type
        - parameters
      properties:
        uuid:
          type: string
          format: uuid
        viewName:
          type: string
        objectUri:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties: true
        state:
          $ref: '#/components/schemas/NavigationTargetState'
        type:
          $ref: '#/components/schemas/NavigationTargetType'
        fullSize:
          type: boolean
          default: false
        title:
          type: string
        icon:
          type: string
    NavigationTargetState:
      type: string
      enum:
        - to_open
        - opening
        - opened
        - to_close
        - closing
        - closed
      default: to_open
    NavigationTargetType:
      type: string
      enum:
        - normal
        - dialog
      default: normal
    Message:
      type: object
      required:
        - uri
        - type
        - possibleResults
      properties:
        uri:
          type: string
          format: URI
        type:
          $ref: '#/components/schemas/MessageType'
        header:
          type: string
        text:
          type: string
        possibleResults:
          type: array
          items:
            $ref: '#/components/schemas/MessageResult'
        selectResult:
          $ref: '#/components/schemas/MessageResult'
    MessageType:
      type: string
      enum:
        - info
        - question
        - warning
        - error
    MessageResult:
      type: object
      properties:
        code:
          type: string
        label:
          type: string
        icon:
          type: string
        type:
          $ref: '#/components/schemas/MessageResultType'
    MessageResultType:
      type: string
      enum:
        - confirm
        - reject
        - cancel
    NavigableViewDescriptor:
      type: object
      properties:
        viewName:
          type: string
        viewClassName:
          type: string
        title:
          type: string
        icon:
          type: string
    Object:
      type: object          
    CommandData:
      type: object
      properties:
        model:
          $ref: '#/components/schemas/Object'
        commandPath:
          type: string
        commandCode:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/Object'
    CommandResult:
      type: object
      properties:
        uiToOpen:
          $ref: '#/components/schemas/NavigationTarget'
        messageToOpen:
          $ref: '#/components/schemas/Message'
        view:
          $ref: '#/components/schemas/ViewModelData'
