openapi: 3.0.1
info:
  title: sb4starter ui api
  description: sb4starter ui api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: SB4StarterUIApi
paths: {}
components:
  schemas:
    SB4StarterModel:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/SB4StarterState'
        startContent:
          type: BinaryContent
        resultContent:
          type: BinaryContent
        SB4StarterUrl:
          type: string
        editCommandKind:
          type: CommandKind
    SB4StarterState:
      type: string
      enum:
      - Letöltés folyamatban
      - Szerkesztés folyamatban
      - Szerkesztés befejezve
      x-enum-varnames:
      - DOWNLOADING
      - EDITING
      - UPLOADED