/*
 * UiTree domain objects
 * Tree domain objects
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.uitree.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.uitree.bean.SmartTreeNode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SmartTreeModel
 */
@JsonPropertyOrder({
  SmartTreeModel.IDENTIFIER,
  SmartTreeModel.ROOT_NODES
})
@JsonTypeName("SmartTreeModel")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SmartTreeModel {
  public static final String IDENTIFIER = "identifier";
  private String identifier;

  public static final String ROOT_NODES = "rootNodes";
  private List<SmartTreeNode> rootNodes = null;

  public SmartTreeModel() { 
  }

  public SmartTreeModel identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public SmartTreeModel rootNodes(List<SmartTreeNode> rootNodes) {
    
    this.rootNodes = rootNodes;
    return this;
  }

  public SmartTreeModel addRootNodesItem(SmartTreeNode rootNodesItem) {
    if (this.rootNodes == null) {
      this.rootNodes = new ArrayList<>();
    }
    this.rootNodes.add(rootNodesItem);
    return this;
  }

   /**
   * Get rootNodes
   * @return rootNodes
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(ROOT_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SmartTreeNode> getRootNodes() {
    return rootNodes;
  }


  @JsonProperty(ROOT_NODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRootNodes(List<SmartTreeNode> rootNodes) {
    this.rootNodes = rootNodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmartTreeModel smartTreeModel = (SmartTreeModel) o;
    return Objects.equals(this.identifier, smartTreeModel.identifier) &&
        Objects.equals(this.rootNodes, smartTreeModel.rootNodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, rootNodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmartTreeModel {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    rootNodes: ").append(toIndentedString(rootNodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

