/*
 * Uitree Api
 * Tree domain objects
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.uitree.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.smartbit4all.api.uitree.bean.UiTreeDefaultSelection;
import org.smartbit4all.api.uitree.bean.UiTreeNode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * This object holds all information about abritrary data in a tree representation.
 */
@Schema(description = "This object holds all information about abritrary data in a tree representation.")
@JsonPropertyOrder({
  UiTreeState.CONFIG,
  UiTreeState.VIEW_UUID,
  UiTreeState.NODES,
  UiTreeState.ROOT_NODES,
  UiTreeState.EXPANDED_NODES,
  UiTreeState.SELECTED_NODES,
  UiTreeState.DEFAULT_SELECTION,
  UiTreeState.PARAMS,
  UiTreeState.VARS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UiTreeState {
  public static final String CONFIG = "config";
  private String config;

  public static final String VIEW_UUID = "viewUuid";
  private UUID viewUuid;

  public static final String NODES = "nodes";
  private Map<String, UiTreeNode> nodes = new HashMap<>();

  public static final String ROOT_NODES = "rootNodes";
  private List<String> rootNodes = new ArrayList<>();

  public static final String EXPANDED_NODES = "expandedNodes";
  private List<String> expandedNodes = new ArrayList<>();

  public static final String SELECTED_NODES = "selectedNodes";
  private List<String> selectedNodes = new ArrayList<>();

  public static final String DEFAULT_SELECTION = "defaultSelection";
  private UiTreeDefaultSelection defaultSelection;

  public static final String PARAMS = "params";
  private Map<String, Object> params = new HashMap<>();

  public static final String VARS = "vars";
  private Map<String, Object> vars = new HashMap<>();

  public UiTreeState() {
  }

  public UiTreeState config(String config) {
    
    this.config = config;
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfig() {
    return config;
  }


  @JsonProperty(CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfig(String config) {
    this.config = config;
  }

  public UiTreeState viewUuid(UUID viewUuid) {
    
    this.viewUuid = viewUuid;
    return this;
  }

  /**
   * Get viewUuid
   * @return viewUuid
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(VIEW_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getViewUuid() {
    return viewUuid;
  }


  @JsonProperty(VIEW_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewUuid(UUID viewUuid) {
    this.viewUuid = viewUuid;
  }

  public UiTreeState nodes(Map<String, UiTreeNode> nodes) {
    
    this.nodes = nodes;
    return this;
  }

  public UiTreeState putNodesItem(String key, UiTreeNode nodesItem) {
    this.nodes.put(key, nodesItem);
    return this;
  }

  /**
   * Get nodes
   * @return nodes
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  @JsonProperty(NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, UiTreeNode> getNodes() {
    return nodes;
  }


  @JsonProperty(NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNodes(Map<String, UiTreeNode> nodes) {
    this.nodes = nodes;
  }

  public UiTreeState rootNodes(List<String> rootNodes) {
    
    this.rootNodes = rootNodes;
    return this;
  }

  public UiTreeState addRootNodesItem(String rootNodesItem) {
    if (this.rootNodes == null) {
      this.rootNodes = new ArrayList<>();
    }
    this.rootNodes.add(rootNodesItem);
    return this;
  }

  /**
   * Get rootNodes
   * @return rootNodes
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  @JsonProperty(ROOT_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getRootNodes() {
    return rootNodes;
  }


  @JsonProperty(ROOT_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRootNodes(List<String> rootNodes) {
    this.rootNodes = rootNodes;
  }

  public UiTreeState expandedNodes(List<String> expandedNodes) {
    
    this.expandedNodes = expandedNodes;
    return this;
  }

  public UiTreeState addExpandedNodesItem(String expandedNodesItem) {
    if (this.expandedNodes == null) {
      this.expandedNodes = new ArrayList<>();
    }
    this.expandedNodes.add(expandedNodesItem);
    return this;
  }

  /**
   * Get expandedNodes
   * @return expandedNodes
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  @JsonProperty(EXPANDED_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getExpandedNodes() {
    return expandedNodes;
  }


  @JsonProperty(EXPANDED_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpandedNodes(List<String> expandedNodes) {
    this.expandedNodes = expandedNodes;
  }

  public UiTreeState selectedNodes(List<String> selectedNodes) {
    
    this.selectedNodes = selectedNodes;
    return this;
  }

  public UiTreeState addSelectedNodesItem(String selectedNodesItem) {
    if (this.selectedNodes == null) {
      this.selectedNodes = new ArrayList<>();
    }
    this.selectedNodes.add(selectedNodesItem);
    return this;
  }

  /**
   * Get selectedNodes
   * @return selectedNodes
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  @JsonProperty(SELECTED_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getSelectedNodes() {
    return selectedNodes;
  }


  @JsonProperty(SELECTED_NODES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelectedNodes(List<String> selectedNodes) {
    this.selectedNodes = selectedNodes;
  }

  public UiTreeState defaultSelection(UiTreeDefaultSelection defaultSelection) {
    
    this.defaultSelection = defaultSelection;
    return this;
  }

  /**
   * Get defaultSelection
   * @return defaultSelection
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(DEFAULT_SELECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UiTreeDefaultSelection getDefaultSelection() {
    return defaultSelection;
  }


  @JsonProperty(DEFAULT_SELECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultSelection(UiTreeDefaultSelection defaultSelection) {
    this.defaultSelection = defaultSelection;
  }

  public UiTreeState params(Map<String, Object> params) {
    
    this.params = params;
    return this;
  }

  public UiTreeState putParamsItem(String key, Object paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

  /**
   * Additional parameters for tree.  
   * @return params
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Additional parameters for tree.  ")
  @JsonProperty(PARAMS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getParams() {
    return params;
  }


  @JsonProperty(PARAMS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setParams(Map<String, Object> params) {
    this.params = params;
  }

  public UiTreeState vars(Map<String, Object> vars) {
    
    this.vars = vars;
    return this;
  }

  public UiTreeState putVarsItem(String key, Object varsItem) {
    if (this.vars == null) {
      this.vars = new HashMap<>();
    }
    this.vars.put(key, varsItem);
    return this;
  }

  /**
   * Variables for tree handling code. It will be cleared (won&#39;t be saved)  at the end of request.  
   * @return vars
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Variables for tree handling code. It will be cleared (won't be saved)  at the end of request.  ")
  @JsonProperty(VARS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getVars() {
    return vars;
  }


  @JsonProperty(VARS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setVars(Map<String, Object> vars) {
    this.vars = vars;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UiTreeState uiTreeState = (UiTreeState) o;
    return Objects.equals(this.config, uiTreeState.config) &&
        Objects.equals(this.viewUuid, uiTreeState.viewUuid) &&
        Objects.equals(this.nodes, uiTreeState.nodes) &&
        Objects.equals(this.rootNodes, uiTreeState.rootNodes) &&
        Objects.equals(this.expandedNodes, uiTreeState.expandedNodes) &&
        Objects.equals(this.selectedNodes, uiTreeState.selectedNodes) &&
        Objects.equals(this.defaultSelection, uiTreeState.defaultSelection) &&
        Objects.equals(this.params, uiTreeState.params) &&
        Objects.equals(this.vars, uiTreeState.vars);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, viewUuid, nodes, rootNodes, expandedNodes, selectedNodes, defaultSelection, params, vars);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UiTreeState {\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    viewUuid: ").append(toIndentedString(viewUuid)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    rootNodes: ").append(toIndentedString(rootNodes)).append("\n");
    sb.append("    expandedNodes: ").append(toIndentedString(expandedNodes)).append("\n");
    sb.append("    selectedNodes: ").append(toIndentedString(selectedNodes)).append("\n");
    sb.append("    defaultSelection: ").append(toIndentedString(defaultSelection)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    vars: ").append(toIndentedString(vars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

