plugins {
    id 'java-test-fixtures'
}

dependencies {
	api project(':api-domain')
	api project(':api')

    implementation 'io.jsonwebtoken:jjwt:0.12.6'

	api 'org.springframework.security:spring-security-oauth2-jose'
	api 'org.springframework.security:spring-security-oauth2-client'
	api 'org.springframework.security:spring-security-config'
	api 'org.springframework.security:spring-security-web'
	api 'org.springframework.session:spring-session-core'
	api 'jakarta.servlet:jakarta.servlet-api:6.0.0'

 	testImplementation 'org.smartbit4all.platform:api'
	testImplementation testFixtures('org.smartbit4all.platform:api')
}
