/*
 * View API
 * View API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.view.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The server request execution statistic is an object for the actuator infrastructure. It is initiated for every view-widget-action and contains the minimum, average and maximum execution times. It collects from the server start. 
 */
@ApiModel(description = "The server request execution statistic is an object for the actuator infrastructure. It is initiated for every view-widget-action and contains the minimum, average and maximum execution times. It collects from the server start. ")
@JsonPropertyOrder({
  ServerRequestExecutionStat.ID,
  ServerRequestExecutionStat.VIEW_NAME,
  ServerRequestExecutionStat.WIDGET_ID,
  ServerRequestExecutionStat.ACTION_CODE,
  ServerRequestExecutionStat.MIN_MS,
  ServerRequestExecutionStat.AVG_MS,
  ServerRequestExecutionStat.MAX_MS,
  ServerRequestExecutionStat.COUNTER,
  ServerRequestExecutionStat.SUM_EXEC_TIME
})
@JsonTypeName("ServerRequestExecutionStat")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServerRequestExecutionStat {
  public static final String ID = "id";
  private String id;

  public static final String VIEW_NAME = "viewName";
  private String viewName;

  public static final String WIDGET_ID = "widgetId";
  private String widgetId;

  public static final String ACTION_CODE = "actionCode";
  private String actionCode;

  public static final String MIN_MS = "minMs";
  private Long minMs;

  public static final String AVG_MS = "avgMs";
  private Long avgMs;

  public static final String MAX_MS = "maxMs";
  private Long maxMs;

  public static final String COUNTER = "counter";
  private Long counter;

  public static final String SUM_EXEC_TIME = "sumExecTime";
  private Long sumExecTime;

  public ServerRequestExecutionStat() { 
  }

  public ServerRequestExecutionStat id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The identifier of the statistical entry. The view - widget - action format.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier of the statistical entry. The view - widget - action format.")
  @JsonProperty(ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ServerRequestExecutionStat viewName(String viewName) {
    
    this.viewName = viewName;
    return this;
  }

   /**
   * The name of the view the request is performed on.
   * @return viewName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the view the request is performed on.")
  @JsonProperty(VIEW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getViewName() {
    return viewName;
  }


  @JsonProperty(VIEW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewName(String viewName) {
    this.viewName = viewName;
  }


  public ServerRequestExecutionStat widgetId(String widgetId) {
    
    this.widgetId = widgetId;
    return this;
  }

   /**
   * The identifier of the widget if it is a widget action perform.
   * @return widgetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier of the widget if it is a widget action perform.")
  @JsonProperty(WIDGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWidgetId() {
    return widgetId;
  }


  @JsonProperty(WIDGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidgetId(String widgetId) {
    this.widgetId = widgetId;
  }


  public ServerRequestExecutionStat actionCode(String actionCode) {
    
    this.actionCode = actionCode;
    return this;
  }

   /**
   * The identifier of the action performed.
   * @return actionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier of the action performed.")
  @JsonProperty(ACTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActionCode() {
    return actionCode;
  }


  @JsonProperty(ACTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionCode(String actionCode) {
    this.actionCode = actionCode;
  }


  public ServerRequestExecutionStat minMs(Long minMs) {
    
    this.minMs = minMs;
    return this;
  }

   /**
   * The minimum execution time of the given action in millisec.
   * @return minMs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The minimum execution time of the given action in millisec.")
  @JsonProperty(MIN_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMinMs() {
    return minMs;
  }


  @JsonProperty(MIN_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinMs(Long minMs) {
    this.minMs = minMs;
  }


  public ServerRequestExecutionStat avgMs(Long avgMs) {
    
    this.avgMs = avgMs;
    return this;
  }

   /**
   * The average execution time of the given action in millisec.
   * @return avgMs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The average execution time of the given action in millisec.")
  @JsonProperty(AVG_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAvgMs() {
    return avgMs;
  }


  @JsonProperty(AVG_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvgMs(Long avgMs) {
    this.avgMs = avgMs;
  }


  public ServerRequestExecutionStat maxMs(Long maxMs) {
    
    this.maxMs = maxMs;
    return this;
  }

   /**
   * The average execution time of the given action in millisec.
   * @return maxMs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The average execution time of the given action in millisec.")
  @JsonProperty(MAX_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMaxMs() {
    return maxMs;
  }


  @JsonProperty(MAX_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxMs(Long maxMs) {
    this.maxMs = maxMs;
  }


  public ServerRequestExecutionStat counter(Long counter) {
    
    this.counter = counter;
    return this;
  }

   /**
   * The number of executed requests.
   * @return counter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of executed requests.")
  @JsonProperty(COUNTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCounter() {
    return counter;
  }


  @JsonProperty(COUNTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCounter(Long counter) {
    this.counter = counter;
  }


  public ServerRequestExecutionStat sumExecTime(Long sumExecTime) {
    
    this.sumExecTime = sumExecTime;
    return this;
  }

   /**
   * The summarized execution time of the request.
   * @return sumExecTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The summarized execution time of the request.")
  @JsonProperty(SUM_EXEC_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSumExecTime() {
    return sumExecTime;
  }


  @JsonProperty(SUM_EXEC_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSumExecTime(Long sumExecTime) {
    this.sumExecTime = sumExecTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerRequestExecutionStat serverRequestExecutionStat = (ServerRequestExecutionStat) o;
    return Objects.equals(this.id, serverRequestExecutionStat.id) &&
        Objects.equals(this.viewName, serverRequestExecutionStat.viewName) &&
        Objects.equals(this.widgetId, serverRequestExecutionStat.widgetId) &&
        Objects.equals(this.actionCode, serverRequestExecutionStat.actionCode) &&
        Objects.equals(this.minMs, serverRequestExecutionStat.minMs) &&
        Objects.equals(this.avgMs, serverRequestExecutionStat.avgMs) &&
        Objects.equals(this.maxMs, serverRequestExecutionStat.maxMs) &&
        Objects.equals(this.counter, serverRequestExecutionStat.counter) &&
        Objects.equals(this.sumExecTime, serverRequestExecutionStat.sumExecTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, viewName, widgetId, actionCode, minMs, avgMs, maxMs, counter, sumExecTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerRequestExecutionStat {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    viewName: ").append(toIndentedString(viewName)).append("\n");
    sb.append("    widgetId: ").append(toIndentedString(widgetId)).append("\n");
    sb.append("    actionCode: ").append(toIndentedString(actionCode)).append("\n");
    sb.append("    minMs: ").append(toIndentedString(minMs)).append("\n");
    sb.append("    avgMs: ").append(toIndentedString(avgMs)).append("\n");
    sb.append("    maxMs: ").append(toIndentedString(maxMs)).append("\n");
    sb.append("    counter: ").append(toIndentedString(counter)).append("\n");
    sb.append("    sumExecTime: ").append(toIndentedString(sumExecTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

