openapi: 3.0.1
info:
  title: apiregister api
  description: The apiregister api is a generic possibility to register remote apis.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Apiregister
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        '200':
          description: nope
                
components:
  schemas:
    ApiInfo:
      type: object
      required: [interfaceQualifiedName, apiIdentifier, protocol]
      properties:
        interfaceQualifiedName:
          type: string
          description: 'The fully qualified name of the interface.'
        apiIdentifier: 
          type: string
          description: 'The unique name of the api to be registered.'
        protocol:
          type: string
          description: 'The protocol which can be used to reach the registered api.'
        parameters:
          type: string
          additionalProperties:
            type: string
    Registration:
      type: object
      required: [id, sourceAppId, targetAppId]
      properties:
        id:
          type: string
          format: uri
        sourceApplication:
          type: string
        sourceAppId:
          type: string
          format: uri
        targetApplication:
          type: string
        targetAppId:
          type: string
          format: uri