openapi: 3.0.1
info:
  title: Attachment api
  description: |
    The attachment api domain is strictly manages the BinaryContentData objects. They are responsible for a simple file with file name, location
    (represented by a dataUri) and a locationKind. The location defines the api that responsible for accessing the given content. It can be the storage
    inline but also any other document management system. 
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Object
    description: Object
paths: {}
components:
  schemas:
    BinaryContentData:
      type: object
      description: |
        The binary content data represent a file with file name and other properties like size, mimetype and hash also. This can be used as
        contained inline object to have reference to a file (the dataUri) at a given location managed by the location handler api.
      required: [dataUri, fileName]
      properties:
        location:
          type: string
          description: The location is a type that can be managed by different APIs to access the given content.
        dataUri:
          type: string
          format: uri
        fileName:
          type: string
        created:
          type: UserActivityLog
        updated:
          type: UserActivityLog
        mimeType:
          type: string
        extension:
          type: string
        size:
          type: integer
          format: int64
        contentHash:
          type: string
