openapi: 3.0.1
info:
  title: collection api
  description: collection api for the stored colections.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: CollectionApi
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        '200':
          description: nope
                
components:
  schemas:
    StoredMapData:
      type: object
      description: |
        The contained storage object for the StoredMap that contains the data as a map of URI mapped by string.
      required: [uri, name, uris]
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        uris:
          type: object
          additionalProperties:
            type: string
            format: uri
    StoredListData:
      type: object
      description: |
        The contained storage object for the StoredList that contains the data as an ordered sequence of URI.
      required: [uri, name, uris]
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        uris:
          type: array
          items:
            type: string
            format: uri
    StoredReferenceData:
      type: object
      description: |
        The contained storage object for the StoredReference that contains an object as data.
      required: [uri, name]
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        refObject:
          type: object
    StoredSequenceData:
      type: object
      description: |
        This object contains an atomic sequence that provides globaly unique incrementing value. Can be used as the
        classic database sequence.
      required: [uri, name]
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        current:
          type: integer
          format: int64
          description: The current value of the sequence.
    StoredCollectionDescriptor:
      type: object
      description: |
        This object can be used as parameter object to name a stored object managed by the CollectionApi.
      required: [uri, name]
      properties:
        name:
          type: string
        schema:
          type: string
        scopeUri:
          type: string
          format: uri
        collectionType:
          enum: [LIST, MAP, REFERENCE]
    VectorValue:
      description: |
        The vector value is the result of an embedding operation of any kind. It can be the result of a text or a picture 
        or whatever else. It is normally constructed by a Converter that creates the result from the input object.
      type: object
      required: [inputType, inputObject, vector]
      properties:
        inputType:
          description: The type of the input object.
          type: string
        inputObject:
          description: The input object itself.
          type: object
          additionalProperties: true
        conversion:
          description: The name fo the conversion algorithm like ada2 in case of string.
          type: string
        vector:
          type: array
          items:
            type: number
            format: float
    VectorSearchResultItem:
      description: |
        The vector search result items.
      type: object
      required: [inputType, inputObject, vector]
      properties:
        id:
          description: The unique identifier of the object found.
        score:
          description: The score of the found item.
        value:          
          $ref: '#/components/schemas/VectorValue'
