openapi: 3.0.1
info:
  title: Composite Object API
  description: Composite Object API
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: CompositeObjectApi
paths: {}
components:
  schemas:
    CompositeObjectDef:
      type: object
      required:
      - uri
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        description:
          type: string
        composeableDefUri:
          type: string
          format: uri
          description: The CompositeObjects's ComposeableObjectDef uri field, which determines the view, icon etc.
        associations:
          type: array
          items:
            $ref: '#/components/schemas/CompositeObjectAssociation'
    CompositeObject:
      type: object
      required:
      - uri
      - objects
      properties:
        uri:
          type: string
          format: uri
        compositeDefUri:
          type: string
          format: uri
          description: The CompositeObjectDef's uri field.
        caption:
          type: string
        objects:
          type: array
          items:
            $ref: '#/components/schemas/ComposeableObject'
    CompositeObjectAssociation:
      type: object
      properties:
        name:
          type: string
          description: Symbolic name of the association. Should be unique in the CompositeObjectDef.
        assocDefUri:
          type: string
          format: uri
        childDefUri:
          type: string
          format: uri
        childRecursive:
          type: boolean
          default: true
    ComposeableObjectDef:
      type: object
      required:
      - uri
      properties:
        uri:
          type: string
          format: uri
        apiUri:
          type: string
          format: uri
        name:
          type: string
        viewName:
          type: string
        icon:
          type: string
        assocVisible:
          type: boolean
    ComposeableObject:
      type: object
      properties:
        defUri:
          type: string
          format: uri
          description: ComposeableObjectDef URI.
        objectUri:
          type: string
          format: uri
