openapi: 3.0.1
info:
  title: content staging api
  description: content staging api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: ContentStaging
paths: {}
components:
  schemas:
    ContentStagingDocument:
      type: object
      properties:
        key:
          type: string
          format: uuid
        uri:
          type: string
          format: uri
        contentUri:
          type: string
          format: uri
        type:
          $ref: '#/components/schemas/Type'
          
    ContentStagingEventData:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Type'
        state:
          $ref: '#/components/schemas/State'
        key:
          type: string
          format: uuid
        contentUri:
          type: string
          format: uri

    Type:
      type: string
      enum:
        - download
        - upload
        
    State:
      type: string
      enum:
        - active
        - uploaded
        - downloaded