openapi: 3.0.1
info:
  title: Grid api
  description: |
    The grid api is resposible for the grid components that shows a list of item.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Grid
    description: Grid
paths: {}
components:
  schemas:
    GridDataAccessConfig:
      type: object
      description: |
        This is the backend object to setup the grid access api. The parameterization contain all the possible
        parameters requiered to identify the API to call or even the InvocationRequest to use. Register into the
        parameters of the View parameters as grid.identifier.config
      required: []
      properties:
        dataUri:
          type: string
          format: uri
          description: The uri of the object that contains the data of the list.
        propertyPath:
          type: string
          description: The property path to access the data of the grid in the referred object.
        apiClass:
          type: string
        kind:
          enum: [TABLEDATA, OBJECTLIST, APIBASED, INVOCATIONS]
    GridModel:
      type: object
      description: |
        This object respresent the model of a grid component.
      required: [viewOptions, page]
      properties:
        viewOptions:
          type: array
          items:
            $ref: '#/components/schemas/GridViewOption'
        page:
          $ref: '#/components/schemas/GridContentPage'
    GridContentPage:
      type: object
      description: |
        This object containt the page information of the content. The currently seen row range, the total row cont and other options.
      required: [columns]
      properties:
        lowerBound:
          type: integer
          format: int32
          description: The index of the first row in the current page. Startes from 1 and inclusive.
        upperBound:
          type: integer
          format: int32
          description: The index of the last row in the current page inclusive.
        pageSize:
          type: integer
          format: int32
        totalRowCount:
          type: integer
          format: int32
        rows:
          type: array
          items:
            $ref: '#/components/schemas/GridRow'
    GridRow:
      type: object
      description: |
        This object is a grid row containening the identifier and actions releted with the row.
      required: [actions]
      properties:
        id:
          type: string
        actions:
          type: array
          items:
            type: UiAction
        data:
          type: object
    GridViewOption:
      type: object
      description: |
        The configuration of the grid view. It can be a simple table grid but a complex card representation also. A model
        has one or more view option to render the content.
      required: [columns]
      properties:
        label:
          type: string
        icon:
          type: string
        kind:
          enum: [TABLE, EXPANDABLECARDS1]
        columns:
          type: array
          items:
            $ref: '#/components/schemas/GridColumnMeta'
    GridColumnMeta:
      type: object
      required: [label, propertyName]
      properties:
        label:
          type: string
        propertyName:
          type: string
        typeClass:
          type: string
