openapi: 3.0.1
info:
  title: invocation api
  description: The invocation api is a generic possibility to call remote apis.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Invocation
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        '200':
          description: nope
                
components:
  schemas:
    InvocationRequestTemplate:
      type: object
      required: [parameters, apiClass, methodName]
      properties:
        executionApi:
          type: string
          description: 'The name of the execution api. If it is empty then we use the local by default'
        apiClass: 
          type: string
          description: 'The fully qualified name of the api. In case of java it is the name of the class.'
        apiInstanceId:
          type: string
          description: The unique identifier for the api instance. If it is set then the execution will be routed to the given instance.
        innerApi:
          type: string
          description: 'If we have a contributed api collecting other apis then it is the identifier of the contributed api.'
        methodName:
          type: string
          description: 'The name of the method to call'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/InvocationParameterTemplate'
    InvocationParameterTemplate:
      type: object
      required: [name, typeClass]
      properties:
        name:
          type: string
          description: The symbolic name of the parameter. Must be set and unique inside an invocation request template.
        defaultValueString:
          type: string
          description: The default value for the given parameter.
        typeClass:
          type: string
          description: The fully qualified type class name of the parameter.
