openapi: 3.0.1
info:
  title: Object api
  description: |
    The object api responsible for the domain object meta information including the object definitions
    and the relations among them. These objects are stored because the modules can contribute. The modules
    have their own ObjectApi that manages the storage and ensure the up-to-date view of the current data.
    The algorithms are running on the ObjectApi cache refreshed periodically.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Object
    description: Object
paths: {}
components:
  schemas:
    ObjectDefinitionData:
      type: object
      description: |
        The object definition can be defined by some API definition language like OpenApi or so. On the backend the result is java class that describes all
        the properties and contained object definitions also.
      required: [uri, properties]
      properties:
        uri:
          type: string
          format: uri
          description: |
            The storage identifier of the given definition. It is calculated by the qualified name of the object. For example 
            object:/com/smartbit4all/mydomain/model/MyObject could be a calculated URI for a given reference. The object definition
        qualifiedName:
          type: string
        properties:
          type: array
          items:
            $ref: '#/components/schemas/PropertyDefinitionData'
    PropertyDefinitionData:
      type: object
      description: |
        The property definition can be defined by some API definition language like OpenApi or so. On the backend the result is java class that describes all
        the properties and contained object definitions also. This definition is responsible for the properties.
      properties:
        uri:
          type: string
          format: uri
          description: |
            The storage identifier of the given definition. It is calculated by the qualified name of the object. For example 
            object:/com/smartbit4all/mydomain/model/MyObject/firstProperty could be a calculated URI for a given reference.
        name:
          type: string
          description: The property name.
        typeClass:
          type: string
          description: |
            The qualified name of the type class in java. Like java.lang.String If we need to convert this type to any other platform then
            we need a conversion for this.
    ReferenceDefinitionData:
      type: object
      description: |
        The reference definition is a directed navigation between objects. Its name is unique inside the source object that can have only one
        outgoing reference with the same name. In the target object the source object and the name is unique together but the name itself is not
        enough to identify an incoming reference.
      required: 
      - "uri"
      - sourceObjectName
      - propertyPath
      - targetObjectName
      - aggregation
      - multiplicity
      properties:
        uri:
          type: string
          format: uri
          description: |
            The storage identifier of the given definition. It is calculated by the qualified name of the object and the name name of the
            reference. For example object:/com/smartbit4all/mydomain/model/MyObject/firstReference could be a calculated URI for a given reference.
            By deafult it could be a good idea to name the reference by the name of the property that contains the reference value.
        backReference:
          type: string
          format: uri
          description: If an association between two object is navigable into both direction then this uri refers to the opposite reference.
        sourceObjectName:
          type: string
          description: The name of the target object.
        propertyPath:
          description:  |
            The descriptor of a property in a domain object. If there is a simple property then we have only the path. The path is a navigation path to
            identify the property in the object or in its contained objects. The path can be "parent" if the parent property is directly a property inside the
            object. It can be myContained/parent if it is the propery of the myContained object. The property must be an uri or unique identifier to be able to 
            access the object directly by its value.
            If we have an array the the array path contains the path of the array property in the same way. The array must contains uri / identifier values.
          type: string
        targetObjectName:
          type: string
          description: The name of the target object.
        aggregation:
          $ref: '#/components/schemas/AggregationKind'
        propertyKind:
          $ref: '#/components/schemas/ReferencePropertyKind'
    AggregationKind:
      type: string
      description: |
        COMPOSITE means that the source contains the target object. The target object is accessible 
        only from the source. NONE means normal reference, no composition. SHARED is not implemented yet.
      default: none
      enum: [none, shared, composite, inline]
    ReferencePropertyKind:
      type: string
      enum: [reference, list, map]
    ObjectNodeData:
      type: object
      description: |
        This object contains an object instance as map. It can be used to separate the references and the business data in the API implementations. The object node contains 
        an object returned by the RetrievalApi. It can manage the state of the object and we can use it to produce ApplyChangeRequest at the end of the modification.
      required: [qualifiedName, versionNr, state, objectAsMap, references, referenceLists, referenceMaps] 
      properties:
        objectUri:
          type: string
          format: uri
          description: |
            The object URI of the given object state. It is version URI to be able to refere to the given version of the data.
        qualifiedName:
          type: string
          description: |
            The qualified globaly unique name of the object definition. In a java application it is the qualified name of the class.
        storageSchema:
          type: string
          description: |
            The logical storage scheme if it is used in the given storage implementation.
        versionNr:
          type: integer
          format: int64
          default: 0
          description: |
            The version number of the given node. It is filled by the retrieve so if we create a new node
            then it is 0 by default.
        state:
          $ref: '#/components/schemas/ObjectNodeState'
        objectAsMap:
          type: object
          additionalProperties: true
        references:
          type: ObjectNodeData
          additionalProperties:
            $ref: '#/components/schemas/ObjectNodeData'
        referenceLists:
          type: ObjectNodeData
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/ObjectNodeData'
        referenceMaps:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/ObjectNodeData'
        resultUri:
          type: string
          format: uri
          description: |
            The object URI after an ObjectApi.save. It can be used to read the result Uri after save.
    ObjectNodeState:
      type: string
      default: NOP
      enum: [NOP, NEW, MODIFIED, REMOVED]
    RetrievalMode:
      type: string
      default: NORMAL
      enum: [NORMAL, LATEST, EXACT_VERSION]
    SnapshotEntry:
      type: object
      description: |
        A snapshot is similar to an ObjectNodeData. It can be saved, and contains only one inline 
        object (SnapshotData) - it only contains versioned URIs and references. 
        Since these versions don't change, a snapshot can always be reloaded exactly as it was before.
      properties:
        uri:
          type: string
          format: uri
        data:
          $ref: '#/components/schemas/SnapshotData'
    SnapshotData:
      type: object
      description: 
      required: [references, referenceLists, referenceMaps] 
      properties:
        objectUri:
          type: string
          format: uri
        qualifiedName:
          type: string
        storageSchema:
          type: string
        versionNr:
          type: integer
          format: int64
        objectAsMap:
          type: object
          additionalProperties: true
        references:
          type: string
          additionalProperties:
            $ref: '#/components/schemas/SnapshotDataRef'
        referenceLists:
          type: string
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/SnapshotDataRef'
        referenceMaps:
          type: string
          additionalProperties:
            type: string
            additionalProperties:
              $ref: '#/components/schemas/SnapshotDataRef'
        resultUri:
          type: string
          format: uri
          description: |
            The object URI after an ObjectApi.save. It can be used to read the result Uri after save.
    SnapshotDataRef:
      type: object
      description: 
      properties:
        objectUri:
          type: string
          format: uri
        isLoaded:
          type: boolean
        data:
          $ref: '#/components/schemas/SnapshotData'
    ObjectChangeData:
      type: object
      description: |
        The changes between two object structure. The change is based on the property names and computed by the value map of
        the object.
      required: [properties, references]
      properties:
        typeClass:
          type: string
          description: The name of the type class if exists.
        properties:
          type: array
          items:
            $ref: '#/components/schemas/PropertyChangeData'
        references:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceChangeData'
    PropertyChangeData:
      type: object
      description: |
        The change of a property with the path as an identifier. The old value and the new value is also available as Object but
        we need to handle it as String after a serialization and deserialization.
      required: [path]
      properties:
        path:
          type: string
          description: The path identify the given property inside the object.
        oldValue:
          type: object
        newValue:
          type: object          
    ReferenceChangeData:
      type: object
      description: |
        The change of a reference in and object as another object change.
      required: [path]
      properties:
        path:
          type: string
          description: The path identify the given property inside the object.
        objectChange:
          $ref: '#/components/schemas/ObjectChangeData'
    TableDataContent:
      type: object
      description: |
        This object is a table data with column definitions as header and rows. The rows are map of objects with the
        property names defined in the header.
      required: [header, totalRowCount, rows]
      properties:
        header:
          $ref: '#/components/schemas/TableDataContentHeader'
        totalRowCount:
          type: integer
          format: int32
        rows:
          type: array
          items:
            $ref: '#/components/schemas/TableDataContentRow'
    TableDataContentRow:
      type: object
      description: |
        This object is a table data row containening the identifier and actions releted with the row.
      required: [actions]
      properties:
        data:
          type: object
    TableDataContentHeader:
      type: object
      description: |
        This object is a table data header that defines the columns of the table data.
      required: [columns]
      properties:
        columns:
          type: array
          items:
            $ref: '#/components/schemas/TableDataContentColumn'
    TableDataContentColumn:
      type: object
      required: [label, propertyName]
      properties:
        label:
          type: string
        propertyName:
          type: string
        typeClass:
          type: string
    ObjectContainer:
      type: object
      required: [uri]
      properties:
        uri:
          type: string
          format: uri
        data:
          type: object
