openapi: 3.0.1
info:
  title: org api
  description: org api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: User
- name: Group
paths:

  #### USER ####

  /getUser/{userUri}:
    get:
      tags:
      - User
      summary: 'Returns the requested User object'
      operationId: 'getUser'
      parameters: 
        - in: path
          name: userUri
          schema:
            type: string
            format: uri
          required: true
          description: 'The URI of the user the data is requested for'
      responses:
        '200':
          description: 'Returns the requested User object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                
  /getAllUsers:
    get:
      tags:
      - User
      summary: 'Returns all users'
      operationId: 'getAllUsers'
      responses:
        '200':
          description: 'Returns all users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    
  /getUsersOfGorup/{groupUri}:
    get:
      tags:
      - User
      summary: 'Returns all users of the specified group'
      operationId: 'getUsersOfGorup'
      parameters: 
        - in: path
          name: groupUri
          schema:
            type: string
            format: uri
          required: true
          description: 'The URI of the group the users are requested from'
      responses:
        '200':
          description: 'Returns all users of the specified group'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /getGroupsOfUser/{userUri}:
    get:
      tags:
      - User
      summary: 'Returns the groups of the specified user'
      operationId: 'getGroupsOfUser'
      parameters: 
        - in: path
          name: userUri
          schema:
            type: string
            format: uri
          required: true
          description: 'The URI of the user the groups are requested from'
      responses:
        '200':
          description: 'Returns the groups of the specified user'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
                  
  #### GROUP ####                
                  
  /getGroup/{groupUri}:
    get:
      tags:
      - Group
      summary: 'Returns the requested Group object'
      operationId: 'getGroup'
      parameters: 
        - in: path
          name: groupUri
          schema:
            type: string
            format: uri
          required: true
          description: 'The URI of the group the data is requested for'
      responses:
        '200':
          description: 'Returns the requested Group object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
                
  /getRootGroups:
    get:
      tags:
      - Group
      summary: 'Returns the groups without parent'
      operationId: 'getRootGroups'
      responses:
        '200':
          description: 'Returns the groups without parent'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'              
                
components:
  schemas:
    User:
      type: object
      required: [uri, attributes]
      properties:
        uri:
          type: string
          format: uri
          description: 'The uri of the user'
        username: 
          type: string
          description: 'The username'
        name: 
          type: string
          description: 'The name fo the user'
        email:
          type: string
          format: email
          description: 'The registered email address that indentifies the user'
        password:
          type: string
          format: password
          description: 'The encripted password of the user'
        inactive:
          type: boolean
          default: false 
        attributes:
          type: object
          additionalProperties:
            type: string
    Group:
      type: object
      required: [uri, name, kind, parent, children]
      properties:
        uri:
          type: string
          format: uri
          description: 'The uri of the group'
        title:
          type: string
          description: 'The title of the group, can be used as display name'
        name:
          type: string
          description: 'The name of the group'
        description:
          type: string
          description: 'The description of the group'
        kindCode:
          type: string
          description: 'The kind code of the group. Eg.: role, organization, team etc.'
        builtIn:
          type: boolean
          default: false
          description: 'Built in groups are unmodifiable'
        parent:
          type: string
          format: uri
          description: 'The uri of the parent group'
        children:
          type: array
          items:
            type: string
            format: uri
          description: 'The uris of the child groups'
    GroupsOfUser:
      type: object
      required: [uri, userUri, groups]
      properties:
        uri:
          type: string
          format: uri
        userUri:
          type: string
          format: uri
        groups:
          type: array
          items:
            type: string
            format: uri
    GroupsOfUserCollection:
      type: object
      required: [uri, groupsOfUserCollection]
      properties:
        uri:
          type: string
          format: uri
        groupsOfUserCollection:
          type: array
          items:
            $ref: '#/components/schemas/GroupsOfUser'  
    UsersOfGroup:
      type: object
      required: [uri, groupUri, users]
      properties:
        uri:
          type: string
          format: uri
        groupUri:
          type: string
          format: uri
        users:
          type: array
          items:
            type: string
            format: uri
    UsersOfGroupCollection:
      type: object
      required: [uri, usersOfGroupCollection]
      properties:
        uri:
          type: string
          format: uri
        usersOfGroupCollection:
          type: array
          items:
            $ref: '#/components/schemas/UsersOfGroup'  