openapi: 3.0.1
info:
  title: sb4starter api
  description: sb4starter api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Sb4starterApi
paths: {}
components:
  schemas:
    SB4Starter:
      type: object
      required: [id, commands]
      additionalProperties: false
      properties:
        id:
          type: string
          format: UUID
        commands:
          type: array
          items:
            $ref: '#/components/schemas/SB4Command'
        keepWorkingDirectory:
          type: boolean
          default: false

    SB4Command:
      type: object
      required: [id, commandKind, restUrl, sb4Files, command, successfulExitCodes, onErrorCommands]
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        commandKind:
          $ref: '#/components/schemas/CommandKind'
        restUrl:
          type: string
          format: uri
          nullable: true
        sb4Files:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/SB4File'
        command:
          type: string
          nullable: true
        successfulExitCodes:
          type: array
          items:
            type: integer
        onErrorCommands:
          type: array
          items:
            $ref: '#/components/schemas/SB4Command'

    CommandKind:
      type: string
      enum:
        - ContentAccessDownload
        - WordEdit
        - ExcelEdit
        - ExecuteCommand
        - ContentAccessUpload
        - ExpandSystemVariable
        
    SB4File:
      type: object
      required: [id, filename]
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        filename:
          type: string
      