openapi: 3.0.1
info:
  title: Security api
  description: Security api...
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Security
    description: Security
paths: {}
components:
  schemas:
    AthenticationResult:
      type: object
      required: 
      - "fullname"
      - "username"
      - "token"
      properties:
        fullname:
          type: string
        username:
          type: string
        token:
          type: string
    ApiKey:
      type: object
      required: [uri, token, user, created, scope]
      description: |
        "Holds information of the user and the token it can use the scoped apis with."
      properties:
        uri:
          description: "The identifier of the api key"
          type: string
          format: uri
        token:
          description: "The generated token which can be used to access apis."
          type: string
        user:
          description: "The URI identifier of the user the api key is created for."
          type: string
          format: uri
        scope:
          description: "The apis that can be accessed with this api key."
          type: array
          items:
            type: string
            format: uri
        expiration:
          description: | 
            "The expiration date of the api key. It can be null, meaning the api key lasts forever
             or until revocation."
          type: string
          format: date-time
        created:
          description: "Information of the creation"
          type: UserActivityLog
        revoked:
          description: |
            "Information of the revocation. It can be null, meaning the token is not revoked."
          type: UserActivityLog
    ApiKeyScope:
      type: object
      required: [uri, name]
      description: |
        "The api scope that tha apiKey can handle"
      properties:
        uri:
          description: "The identifier of the api key"
          type: string
          format: uri
        name:
          type: string
        pathPattern:
          description: "A regex pattern that will be used to validate the incoming http request uri."
          type: string
    OAuthClientProperties:
      type: object
      required:
        - registrationId
        - clientId
        - clientSecret
        - userNameAttribute
        - label
      properties:
        uri:
          type: string
          format: uri
        registrationId:
          type: string
          description: "The registration identifier that app uses to identify the client registration"
        clientId:
          type: string
          description: "The client ID of the OAuth client used by the IDM"
        clientSecret:
          type: string
          description: "The client secret of the OAuth client provided by the IDM"
        clientName:
          type: string
          description: "Sets the logical name of the client or registration. Can be null"
        authorizationUri:
          type: string
          description: "The authorization URI of the OAuth provider"
        tokenUri:
          type: string
          description: "The token URI of the OAuth provider"
        userInfoUri:
          type: string
          description: "The user info URI of the OAuth provider"
        jwkSetUri:
          type: string
          description: "The jwk set URI of the OAuth provider"
        issuerUri:
          type: string
          description: |
            "URI that can either be an OpenID Connect discovery endpoint or an OAuth 2.0
             Authorization Server Metadata endpoint defined by RFC 8414."
        redirectUri:
          type: string
          description: "The redirect URI for the OAuth client"
          default: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        scope:
          type: string
          description: "The scope of the OAuth client, comma-separated"
          example: "openid, profile, email, roles"
        authorizationGrantType:
          type: string
          description: "The authorization grant type of the OAuth client"
          example: "authorization_code"
        userNameAttribute:
          type: string
          description: "The attribute of the user that can be used to identify the username"
          example: "preferred_username"
        userInfoAuthenticationMethod:
          type: string
          description: | 
            "The authentication method used when sending bearer access tokens in resource requests 
             to resource servers. Possible values: header/form/query."
          example: "header"
        commonProvider:
          type: string
          description: |
            "It is possible to set this attribute to use one of the common providers without setting
             all config fields. Possible common providers: facebook, google, github, okta."
        logoutOidcEnabled:
          type: boolean
          description: "With this field the oidc logout can be enabled."
        logoutEndSessionEndpoint:
          type: string
          description: |
            "When auto discovery of oidc endoints is not active (issuerUri is not set), 
            then this field can be used to explicitly configure the logout url"
        logoutRedirectPath:
          type: string
          description: |
            "The redirect path that the IDM can redirect to after logout. {baseUrl} can be used."
        label:
          type: string
          description: "The text that can be used on ui"
        logo:
          type: string
          description: "The logo that can be used on ui. TBD"
        userParameterMapping:
          type: object
          description: |
            "This mapping contains the user attribute names stored in the application and the 
            corresponding attributes stored in the oauth realm. The key is the application, the 
            value is the realm attribute name."
          additionalProperties:
            type: string
        isUserWithoutGroupAllowedToLogIn:
          description: |
            "When true, users without groups can not log in into the application."
          type: boolean
          default: false
        defaultGroupName:
          description: |
            "The name of the SecurityGroup that the logged in user is added to as default."
          type: string
        roleAttributes:
          description: |
            "The attributes sent by the identity provider holding the lists of the role names."
          type: array
          items:
            type: string
        roleMapping:
          type: object
          description: |
            "This mapping contains the users' role names stored in the oauth realm and the 
            corresponding group names stored in the application . The key is the realm role name, 
            the value is the application group name."
          additionalProperties:
            type: string