openapi: 3.0.1
info:
  title: Session api
  description: Session api...
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Session
paths:
  /session:
    put:
      tags:
      - Session
      summary: Creates a new session
      operationId: 'startSession'
      responses:
        '200':
          description: 'The session has started'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfoData'
        '500':
          description: 'Error during session creation'
    get:
      tags:
      - Session
      summary: Returns the existing session info
      operationId: 'getSession'
      responses:
        '200':
          description: 'Returns the existing session info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfoData'
        '400':
          description: 'Missing JWT token'
        '404':
          description: 'The session does not exists with the given token'
        '500':
          description: 'Error occured while fetching the session data'
  /authenticationProviders:
    get:
      tags:
      - Session
      summary: Returns the available authentication providers
      operationId: 'getAuthenticationProviders'
      responses:
        '200':
          description: 'Returns the available authentication providers'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthenticationProvidersResponse'
        '400':
          description: 'Missing JWT token'
        '404':
          description: 'The session does not exists with the given token'
        '500':
          description: 'Error occured while fetching the session data'
components:
  schemas:
    Session:
      type: object
      required: [authentications,viewContexts]
      properties:
        uri:
          type: string
          format: uri
        expiration:
          type: string
          format: date-time
        locale:
          type: string
        authentications:
          type: array
          items:
            $ref: '#/components/schemas/AccountInfo'
        user:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: string
        viewContexts:
          description: ViewContexts in this session, URIs by UUID.
          type: object
          additionalProperties:
            type: string
            format: uri
    SessionInfoData:
      type: object
      required: [sid]
      properties:
        sid:
          type: string
        expiration:
          type: string
          format: date-time
        locale:
          type: string
        authentications:
          type: array
          items:
            $ref: '#/components/schemas/AccountInfo'
    AccountInfo:
      type: object
      required: [kind, userName, displayName]
      properties:
        kind:
          type: string
        userName:
          type: string
        displayName:
          type: string
        imageContent:
          type: string
          format: byte # or binary?
        imageFormat:
          type: string
        roles:
          type: array
          items:
            type: string
        parameters:
          type: object
          additionalProperties:
            type: string
    GetAuthenticationProvidersResponse:
      type: object
      required: [authenticationProviders]
      properties:
        authenticationProviders:
          type: array
          items:
            $ref: '#/components/schemas/AuthenticationProviderData'
    AuthenticationProviderData:
      type: object
      required: [kind]
      properties:
        kind:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: string
