openapi: 3.0.1
info:
  title: storage api
  description: The storage api is a generic possibility to store and load objects.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Storage
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        '200':
          description: nope
                
components:
  schemas:
    ObjectReferenceList:
      type: object
      description: |
        The list of references as a container object for the Api. 
      required: [uri, references]
      properties:
        uri:
          type: string
          format: uri
          description: The uri of the object
        referenceTypeClass:
          type: string
          description: |
            The type of the reference. It can be the qualified name of the java bean class or anything else that can exactly identify
            the type of the reference object.  
        references:
          type: array
          items:
            $ref: '#/components/schemas/ObjectReference'
    ObjectReference:
      type: object
      description: |
        In generally if we have an object stored by a Storage then we might need to store some object references for this. 
        The related object references are more or less a list of URI or other identifier easy to serialize in every storage mechanism. 
        The Storage can publish events when the given object is changed. This can be filtered by this register. 
        The reference can be temporary so we can define a time limit when the Storage will remove the reference. 
        The relation can be renewed by adding it again and again. This object itself is managed by the ObjectStorage to store this in an 
        optimal way for the given storage mechanism.

      required: [name, typeClass]
      properties:
        referenceId:
          type: string
          description: The identifier of the referenced object. Usually this is an URI that identifies the object in the domain.
        expirationTime:
          type: string
          format: date-time
          description: The expiration time for the reference.
