openapi: 3.0.1
info:
  title: Toolbar API
  description: Toolbar API
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: Toolbar
paths: {}

components:
  schemas:
    ActionDefinition:
      type: object
      description: |
        This is the registry entry of the UiActions in the MDM Entry of the registry.
      required: [uri, qualifiedName, invocations]
      properties:
        uri:
          type: string
          format: uri
        precedenceOrder:
          description: |
            A numerical value and that defines the precedence in a increasing order. It defines that we get the smallest precedence 
            first and override it with the next one and so on.
          type: integer
          format: int32
        qualifiedName:
          description: |
            The namespace and the code of the given action. The action must be unique inside a namespace. It could be important to
            have the same action in different namespaces. The namespace can be the name of an object or even a special page. The last 
            segment is the code itself.
          type: string
        action:
          description: The action itself with the well know parameters.
          $ref: '#/components/schemas/UiAction'
        invocations:
          description: |
            Invocations of the invocation chain behind the action. This invocations are executed when the given
            action is performed.
          type: array
          items:
            type: InvocationRequest
        descriptor:
          description: |
            The UiAction descriptor for the action. If it is set then the it overrides the action.descriptor.
          $ref: '#/components/schemas/UiActionDescriptor'
        contextChecks:
          description: |
            Invocation requests that check the context objects of the action and produce constraints for them if necessary.
            In this check we can remove the given action or disable.
          type: array
          items:
            type: InvocationRequest
    ToolbarDefinition:
      type: object
      description: |
        This is the registry entry of the toolbars in the MDM Entry of the registry. This object defines a menu / toolbar
        in the application. It has a naming that can be referred from the source code of the page. The result is that the
        ToolbarManagementApi produces the UiActions on a Page with the proper settings. The toolbars can be hierarchical for
        hierarchical menus.
      required: [uri, qualifier, code, items]
      properties:
        uri:
          type: string
          format: uri
        precedenceOrder:
          description: |
            A numerical value and that defines the precedence in a increasing order. It defines that we get the smallest precedence 
            first and override it with the next one and so on.
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/ToolbarDefinitionData'
    ToolbarDefinitionData:
      type: object
      description: |
        This is the registry entry of the toolbars in the MDM Entry of the registry. This object defines a menu / toolbar
        in the application. It has a naming that can be referred from the source code of the page. The result is that the
        ToolbarManagementApi produces the UiActions on a Page with the proper settings. The toolbars can be hierarchical for
        hierarchical menus.
      required: [uri, qualifiedName, items]
      properties:
        uri:
          type: string
          format: uri
        qualifiedName:
          description: |
            The namespace and the name of the toolbar. The code should be the unique name of the toolbar on the page and it is
            the last segment.
          type: string
        items:
          description: |
            The ites on the toolbar.
          type: array
          items:
            $ref: '#/components/schemas/ToolbarItem'
        itemProducer:
          description: |
            If we set the item producer logic then the items of the toolbar are coming from this invocation. In this case the
            items must be managed in the invocation call not here. It can be a workflow or a specific menu settings that can produce
            menu items dynamically.
          type: InvocationRequest
    ToolbarItem:
      type: object
      description: |
        This object is one item on the toolbar. The most tipical that it is an action referring to the action registry.
      required: [uri, qualifier, code, items]
      properties:
        uri:
          type: string
          format: uri
        kind:
          description: |
            The kind of the item that can be an action.
          $ref: '#/components/schemas/ToolbarItemKind'
        operation:
          $ref: '#/components/schemas/ToolbarItemOperation'
        referredToolbar:
          description: |
            The qualified name fo the referenced toolbar that defines the inline items or the sub menu items.
          type: string
        toolbar:
          description: |
            The inline toolbar that defines the inline items or the sub menu items. Its qualified name is the
            qualified name of this toolbar + "." + this name.
          $ref: '#/components/schemas/ToolbarDefinitionData'
        action:
          description: |
            The qualified name of the action.
          type: string
        actionDefinitionUri:
          description: |
            asd
          type: string
          format: uri
        descriptor:
          description: |
            The UiAction descriptor for the action if we would like to override it in the give toolbar.
          $ref: '#/components/schemas/UiActionDescriptor'
    ToolbarItemKind:
      enum: [action, inline, submenu]
    ToolbarItemOperation:
      enum: [addBefore, addAfter, addFirst, addLast, remove]

    ViewEvaluationContext:
      type: object
      properties:
        view:
          $ref: '#/components/schemas/View'
        user: # not needed if clients run in the same security context as the related request
          type: string
          format: uri
        model:
          type: object # not strictly needed if clients can automatically run after initModel()
        refreshWidgetsRequired:
          type: boolean
          default: false
        actionReevaluationRequired:
          type: boolean
          default: false
