openapi: 3.0.1
info:
  title: UiAction domain object
  description: UiAction domain objects
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: uiAction
    description: uiAction
paths: {}
components:
  schemas:
    UiAction:
      type: object
      properties:
        code:
          type: string
        apiName:
          type: string
        apiFunction:
          type: string
