openapi: 3.0.1
info:
  title: Uitree Api
  description: Tree domain objects
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: tree
    description: tree
paths:
  /tree/{viewUuid}/{treeId}:
    get:
      tags:
      - tree
      description: Query all tree nodes.
      operationId: getRootNodes
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of SmartTreeNode objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/action:
    get:
      tags:
      - tree
      description: Query all tree nodes.
      operationId: getMainActions
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of UiAction objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: UiAction
    post:
      tags:
      - tree
      description: |
        Performs an action on the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the SmartTreeNode which the action was performed on.
      operationId: performMainAction
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: UiActionRequest
      responses:
        '200':
          description: Changed tree state.
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/{nodeId}:
    get:
      tags:
      - tree
      description: Query the child nodes of the tree's node given in the parameter
      operationId: getChildrenNodes
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of SmartTreeNode objects
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/{nodeId}/expand:
    post:
      tags:
      - tree
      description: |
        Expands the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui, if any.
        Returns the expanded SmartTreeNode.
      operationId: expandNode
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Expanded SmartTreeNode object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/{nodeId}/collapse:
    post:
      tags:
      - tree
      description: |
        Collapses the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the collapsed SmartTreeNode.
      operationId: collapseNode
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Collapsed SmartTreeNode object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/{nodeId}/select:
    post:
      tags:
      - tree
      description: |
        Collapses the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the collapsed SmartTreeNode.
      operationId: selectNode
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Collapsed SmartTreeNode object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SmartTreeNode'
  /tree/{viewUuid}/{treeId}/{nodeId}/action:
    post:
      tags:
      - tree
      description: |
        Performs an action on the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the SmartTreeNode which the action was performed on.
      operationId: performAction
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: UiActionRequest
      responses:
        '200':
          description: Changed tree state.
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/SmartTreeNode'

# tree v2, uses only ViewContextChange as result

  /tree2/{viewUuid}/{treeId}:
    get:
      tags:
      - tree
      description: Query all tree nodes.
      operationId: getRootNodes2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = list of SmartTreeNode objects
          content:
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/action:
    get:
      tags:
      - tree
      description: Query all tree nodes.
      operationId: getMainActions2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = list of UiAction objects
          content:
            application/json:
              schema: 
                type: ViewContextChange
    post:
      tags:
      - tree
      description: |
        Performs an action on the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the SmartTreeNode which the action was performed on.
      operationId: performMainAction2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: UiActionRequest
      responses:
        '200':
          description: ViewContextChange where result = changed tree state
          content: 
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/{nodeId}:
    get:
      tags:
      - tree
      description: Query the child nodes of the tree's node given in the parameter
      operationId: getChildrenNodes2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = list of SmartTreeNode objects
          content: 
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/{nodeId}/expand:
    post:
      tags:
      - tree
      description: |
        Expands the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui, if any.
        Returns the expanded SmartTreeNode.
      operationId: expandNode2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = expanded SmartTreeNode object
          content: 
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/{nodeId}/collapse:
    post:
      tags:
      - tree
      description: |
        Collapses the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the collapsed SmartTreeNode.
      operationId: collapseNode2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = collapsed SmartTreeNode object
          content: 
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/{nodeId}/select:
    post:
      tags:
      - tree
      description: |
        Collapses the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the collapsed SmartTreeNode.
      operationId: selectNode2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ViewContextChange where result = collapsed SmartTreeNode object
          content: 
            application/json:
              schema: 
                type: ViewContextChange
  /tree2/{viewUuid}/{treeId}/{nodeId}/action:
    post:
      tags:
      - tree
      description: |
        Performs an action on the given treenode. The viewcontext will hold the appropriate instruction 
        for the ui.
        Returns the SmartTreeNode which the action was performed on.
      operationId: performAction2
      parameters: 
        - in: path
          name: viewUuid
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: treeId
          schema:
            type: string
          required: true
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: UiActionRequest
      responses:
        '200':
          description: ViewContextChange where result = changed tree state.
          content: 
            application/json:
              schema: 
                type: ViewContextChange
components:
  schemas:
    SmartTreeNode:
      type: object
      required: [classes, childrenNodes, actions]
      properties:
        identifier:
          type: string
        icon:
          type: string
        caption:
          type: string
        classes:
          type: array
          items:
            type: string
        hasChildren:
          type: boolean
        childrenNodes:
          type: array
          items:
            $ref: "#/components/schemas/SmartTreeNode"
        expanded:
          type: boolean
        selected:
          type: boolean
        level:
          type: integer
        shortDescription:
          type: string
        nodeType: 
          type: string
        actions:
          type: array
          items:
            type: UiAction
        
    UiTreeState:
      type: object
      description: This object holds all information about abritrary data in a tree representation.
      required: [nodes, rootNodes, expandedNodes, selectedNodes]
      properties:
        config:
          type: string
        viewUuid:
          type: string
          format: uuid
        nodes:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/UiTreeNode"
        rootNodes:
          type: array
          items:
            type: string
        expandedNodes:
          type: array
          items:
            type: string
        selectedNodes:
          type: array
          items:
            type: string
        defaultSelection:
          $ref: '#/components/schemas/UiTreeDefaultSelection'
        params:
          description: |
            Additional parameters for tree. 
          type: object
          additionalProperties: true
    UiTreeNode:
      type: object
      required: [classes, children, actions]
      properties:
        objectUri:
          type: string
          format: uri
        branchUri:
          type: string
          format: uri
        identifier:
          type: string
        parentIdentifier:
          type: string
        icon:
          type: string
        caption:
          type: string
        classes:
          type: array
          items:
            type: string
        hasChildren:
          type: boolean
          default: false
        children:
          type: array
          items:
            type: string
        level:
          type: integer
        shortDescription:
          type: string
        nodeType: 
          type: string
        actions:
          type: array
          items:
            type: UiAction
    UiTreePath:
      type: object
      required: [parts]
      properties:
        parts:
          type: array
          items:
            $ref: '#/components/schemas/UiTreePathPart'
    UiTreePathPart:
      type: object
      properties:
        objectUri:
          type: string
          format: uri
        nodeType:
          type: string
    UiTreeDefaultSelection:
      type: object
      description: |
        Describes the default selected node of the tree after rendering.
      properties:
        path:
          $ref: '#/components/schemas/UiTreePath'
        handleSelection:
          type: boolean
          default: false
          description: |
            Signals whether the tree should handle the default selected node after rendering.
        oneTimeOnly:
          type: boolean
          default: true
          description: |
            Signals whether the selection should be set only during initialisation, or every time
            the tree is rendered.
      required: [path, handleSelection, oneTimeOnly]