openapi: 3.0.1
info:
  title: UiTree domain objects
  description: Tree domain objects
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: tree
    description: tree
paths: {}
components:
  schemas:
    SmartTreeNode:
      type: object
      required: [classes, childrenNodes, actions]
      properties:
        identifier:
          type: string
        icon:
          type: string
        caption:
          type: string
        classes:
          type: array
          items:
            type: string
        hasChildren:
          type: boolean
        childrenNodes:
          type: array
          items:
            $ref: "#/components/schemas/SmartTreeNode"
        expanded:
          type: boolean
        selected:
          type: boolean
        level:
          type: integer
        shortDescription:
          type: string
        nodeType: 
          type: string
        actions:
          type: array
          items:
            type: UiAction
        
    UiTreeState:
      type: object
      description: This object holds all information about abritrary data in a tree representation.
      required: [nodes, rootNodes, expandedNodes, selectedNodes]
      properties:
        nodes:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/UiTreeNode"
        rootNodes:
          type: array
          items:
            type: string
        expandedNodes:
          type: array
          items:
            type: string
        selectedNodes:
          type: array
          items:
            type: string
        
    UiTreeNode:
      type: object
      required: [classes, children, actions]
      properties:
        objectUri:
          type: string
          format: uri
        branchUri:
          type: string
          format: uri
        identifier:
          type: string
        parentIdentifier:
          type: string
        icon:
          type: string
        caption:
          type: string
        classes:
          type: array
          items:
            type: string
        hasChildren:
          type: boolean
          default: false
        children:
          type: array
          items:
            type: string
        level:
          type: integer
        shortDescription:
          type: string
        nodeType: 
          type: string
        actions:
          type: array
          items:
            type: UiAction
