openapi: 3.0.1
info:
  title: User selector api
  description: User selector ui api.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: UserSelector
paths: {}
components:
  schemas:
    UserSingleSelector:
      type: object
      properties:
        selectors:
          type: array
          items:
            $ref: '#/components/schemas/UserSelector'
        selected:
          $ref: '#/components/schemas/UserSelector'
    UserMultiSelector:
      type: object
      properties:
        selectors:
          type: array
          items:
            $ref: '#/components/schemas/UserSelector'
        selected:
          type: array
          items:
            $ref: '#/components/schemas/UserSelector'
        isSaving:
          type: boolean
    UserSelector:
      type: object
      properties:
        kind:
          type: string
          enum:
          - USER
          - GROUP
        uri:
          type: string
          format: uri
        displayName:
          type: string
        