/*
 * org api
 * org api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.org.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.org.bean.ACLEntry;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The ACL config can be attached as aspect to every object in the storage. This describes available oparations for the subjects. The subjects can be contributed by adding new AccessControlApi to the application. It defines the available subjects and produce the list of subjects a given user belongs to. It does not have any uri because it usually saved as aspect or inner object as well. 
 */
@ApiModel(description = "The ACL config can be attached as aspect to every object in the storage. This describes available oparations for the subjects. The subjects can be contributed by adding new AccessControlApi to the application. It defines the available subjects and produce the list of subjects a given user belongs to. It does not have any uri because it usually saved as aspect or inner object as well. ")
@JsonPropertyOrder({
  ACL.ENTRIES
})
@JsonTypeName("ACL")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ACL {
  public static final String ENTRIES = "entries";
  private List<ACLEntry> entries = new ArrayList<>();

  public ACL() { 
  }

  public ACL entries(List<ACLEntry> entries) {
    
    this.entries = entries;
    return this;
  }

  public ACL addEntriesItem(ACLEntry entriesItem) {
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(ENTRIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ACLEntry> getEntries() {
    return entries;
  }


  @JsonProperty(ENTRIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntries(List<ACLEntry> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ACL ACL = (ACL) o;
    return Objects.equals(this.entries, ACL.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ACL {\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

