/*
 * org api
 * org api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.org.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.net.URI;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * UserEntry
 */
@JsonPropertyOrder({
  UserEntry.URI,
  UserEntry.USER_URI,
  UserEntry.USER_IDENTIFIER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class UserEntry {
  public static final String URI = "uri";
  private URI uri;

  public static final String USER_URI = "userUri";
  private URI userUri;

  public static final String USER_IDENTIFIER = "userIdentifier";
  private String userIdentifier;

  public UserEntry() {
  }

  public UserEntry uri(URI uri) {
    
    this.uri = uri;
    return this;
  }

  /**
   * The uri of the UserEntry
   * @return uri
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The uri of the UserEntry")
  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getUri() {
    return uri;
  }


  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(URI uri) {
    this.uri = uri;
  }

  public UserEntry userUri(URI userUri) {
    
    this.userUri = userUri;
    return this;
  }

  /**
   * The uri of the user
   * @return userUri
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The uri of the user")
  @JsonProperty(USER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUserUri() {
    return userUri;
  }


  @JsonProperty(USER_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserUri(URI userUri) {
    this.userUri = userUri;
  }

  public UserEntry userIdentifier(String userIdentifier) {
    
    this.userIdentifier = userIdentifier;
    return this;
  }

  /**
   * The identifier of the user.
   * @return userIdentifier
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The identifier of the user.")
  @JsonProperty(USER_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserIdentifier() {
    return userIdentifier;
  }


  @JsonProperty(USER_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserIdentifier(String userIdentifier) {
    this.userIdentifier = userIdentifier;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEntry userEntry = (UserEntry) o;
    return Objects.equals(this.uri, userEntry.uri) &&
        Objects.equals(this.userUri, userEntry.userUri) &&
        Objects.equals(this.userIdentifier, userEntry.userIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, userUri, userIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEntry {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    userUri: ").append(toIndentedString(userUri)).append("\n");
    sb.append("    userIdentifier: ").append(toIndentedString(userIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

