CREATE TABLE OBJECT_ENTRY(
  URI VARCHAR2(500) NOT NULL,
  ID NUMBER(38) NOT NULL,
  SCHEME VARCHAR2(150) NOT NULL,
  CLASSNAME VARCHAR2(500) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  UUID VARCHAR2(50) NULL,
  VERSION NUMBER(18) NOT NULL,
  REFVERSION NUMBER(18) NULL,
  SINGLEVERSION VARCHAR2(10) NOT NULL
);

ALTER TABLE OBJECT_ENTRY ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX OBJECT_ENTRY_URI ON OBJECT_ENTRY (URI);
CREATE UNIQUE INDEX OBJECT_ENTRY_URI_ID ON OBJECT_ENTRY (URI, ID);

CREATE TABLE OBJECT_VERSION(
  VERSION_ID VARCHAR2(250) NOT NULL,
  ENTRY_ID NUMBER(38) NOT NULL,
  VERSION NUMBER(18) NOT NULL,
  TRANSACTION_ID VARCHAR2(50) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATEDBYURI VARCHAR2(500) NULL,
  CREATEDBY VARCHAR2(250) NULL,
  OPERATION VARCHAR2(50) NULL,
  REBASEDFROMURI VARCHAR2(500) NULL,
  COMMONANCESTORURI VARCHAR2(500) NULL,
  MERGEDWITHURI VARCHAR2(500) NULL,
  OBJECT_CONTENT_COMPRESS_TYPE VARCHAR2(50) NULL,
  OBJECT_CONTENT BLOB NULL,
  REF_CONTENT BLOB NULL,
  ASPECT_CONTENT BLOB NULL
);

ALTER TABLE OBJECT_VERSION ADD PRIMARY KEY (VERSION_ID);
CREATE UNIQUE INDEX OBJECT_VERSION_IDX_1 ON OBJECT_VERSION (ENTRY_ID, VERSION);

CREATE TABLE OBJECT_ENTRY_LOCK(
  OBJECT_URI VARCHAR2(500) NOT NULL,
  APPLICATIONRUTIME VARCHAR2(50) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL
);

ALTER TABLE OBJECT_ENTRY_LOCK ADD PRIMARY KEY (OBJECT_URI);
CREATE UNIQUE INDEX OBJECT_ENTRY_LOCK_IDX_1 ON OBJECT_ENTRY_LOCK (OBJECT_URI, APPLICATIONRUTIME, CREATED_AT);

CREATE TABLE APPLICATIONRUNTIME(
  URI VARCHAR2(500) NOT NULL,
  UUID VARCHAR2(50) NOT NULL,
  BASEURL VARCHAR2(500) NULL,
  SERVER_PORT NUMBER(18) NOT NULL,
  STARTUPTIME NUMBER(38) NULL,
  STOPTIME NUMBER(38) NULL,
  TIMEOFFSET NUMBER(38) NULL,
  LASTTOUCHTIME NUMBER(38) NULL,
  OBJECT_CONTENT BLOB NULL
);

ALTER TABLE APPLICATIONRUNTIME ADD PRIMARY KEY (UUID);
CREATE UNIQUE INDEX APPLICATIONRUNTIME_IDX_1 ON APPLICATIONRUNTIME (URI, UUID, BASEURL, SERVER_PORT, STARTUPTIME, STOPTIME, TIMEOFFSET, LASTTOUCHTIME);
CREATE UNIQUE INDEX APPLICATIONRUNTIME_IDX_2 ON APPLICATIONRUNTIME (URI);


CREATE SEQUENCE SEQ_OBJECT;
