CREATE TABLE OBJECT_ENTRY(
  URI VARCHAR2(500) NOT NULL,
  ID NUMBER(38) NOT NULL,
  SCHEME VARCHAR2(150) NOT NULL,
  CLASSNAME VARCHAR2(500) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  UUID VARCHAR2(50) NULL,
  VERSION NUMBER(18) NOT NULL,
  REFVERSION NUMBER(18) NULL,
  SINGLEVERSION VARCHAR2(10) NOT NULL
);

ALTER TABLE OBJECT_ENTRY ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX OBJECT_ENTRY_URI ON OBJECT_ENTRY (URI);

CREATE TABLE OBJECT_VERSION(
  VERSION_ID VARCHAR2(250) NOT NULL,
  ENTRY_ID NUMBER(38) NOT NULL,
  VERSION NUMBER(18) NOT NULL,
  TRANSACTION_ID VARCHAR2(50) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATEDBYURI VARCHAR2(500) NULL,
  CREATEDBY VARCHAR2(250) NULL,
  OPERATION VARCHAR2(50) NULL,
  REBASEDFROMURI VARCHAR2(500) NULL,
  COMMONANCESTORURI VARCHAR2(500) NULL,
  MERGEDWITHURI VARCHAR2(500) NULL,
  OBJECT_CONTENT BLOB NULL,
  REF_CONTENT BLOB NULL,
  ASPECT_CONTENT BLOB NULL
);

ALTER TABLE OBJECT_VERSION ADD PRIMARY KEY (VERSION_ID);
CREATE UNIQUE INDEX OBJECT_VERSION_IDX_1 ON OBJECT_VERSION (ENTRY_ID, VERSION);

CREATE SEQUENCE SEQ_OBJECT;
