CREATE UNIQUE INDEX OBJECT_ENTRY_URI ON OBJECT_ENTRY (URI, ID);

CREATE UNIQUE INDEX OBJECT_VERSION_IDX_1 ON OBJECT_VERSION (ENTRY_ID, VERSION);

CREATE UNIQUE INDEX OBJECT_ENTRY_LOCK_IDX_1 ON OBJECT_ENTRY_LOCK (OBJECT_URI, APPLICATIONRUTIME, CREATED_AT);

CREATE UNIQUE INDEX APPLICATIONRUNTIME_IDX_1 ON APPLICATIONRUNTIME (URI, UUID, BASEURL, SERVER_PORT, STARTUPTIME, STOPTIME, TIMEOFFSET, LASTTOUCHTIME);
