CREATE TABLE OBJECT_ENTRY(
  URI VARCHAR2(500) NOT NULL,
  ID NUMBER(38) NOT NULL,
  SCHEME VARCHAR2(150) NOT NULL,
  CLASSNAME VARCHAR2(500) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  UUID VARCHAR2(50) NULL,
  VERSION NUMBER(18) NOT NULL,
  SINGLEVERSION VARCHAR2(10) NOT NULL
);

ALTER TABLE OBJECT_ENTRY ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX OBJECT_ENTRY_URI ON OBJECT_ENTRY (URI);

CREATE TABLE OBJECT_VERSION(
  ENTRY_ID NUMBER(38) NOT NULL,
  VERSION NUMBER(18) NOT NULL,
  TRANSACTION_ID VARCHAR2(50) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATEDBYURI VARCHAR2(500) NULL,
  CREATEDBY VARCHAR2(250) NULL,
  OPERATION VARCHAR2(50) NULL,
  REBASEDFROMURI VARCHAR2(500) NULL,
  COMMONANCESTORURI VARCHAR2(500) NULL,
  MERGEDWITHURI VARCHAR2(500) NULL,
  OBJECT_CONTENT BLOB NULL,
  REF_CONTENT BLOB NULL,
  ASPECT_CONTENT BLOB NULL
);

CREATE SEQUENCE SEQ_OBJECT;

CREATE TABLE PROCESS_ACTIVITY_LOG(
  ID NUMBER(38) NOT NULL,
  PROCESS_URI VARCHAR2(500) NOT NULL,
  PROCESS_NAME VARCHAR2(500) NULL,
  STEP_CODE VARCHAR2(500) NULL,
  STEP_NAME VARCHAR2(500) NULL,
  ENTRY_AT TIMESTAMP NOT NULL,
  EXIT_AT TIMESTAMP NULL,
  SESSIONID VARCHAR2(500) NULL
);

CREATE TABLE PROCESS_ACTIVITY_OBJECT(
  LOG_ID NUMBER(38) NOT NULL,
  OBJECT_ID VARCHAR2(500) NOT NULL,
  VERSION NUMBER(18) NULL
);


/*
SELECT pal.PROCESS_URI, pal.STEP_CODE, pal.STEP_NAME,
       JSON_VALUE(DBMS_LOB.SUBSTR(ov.OBJECT_CONTENT, 4000, 1), '$.ChildData') AS ChildData
FROM PROCESS_ACTIVITY_LOG pal
JOIN PROCESS_ACTIVITY_OBJECT pao
  ON pal.ID = pao.LOG_ID AND pao.OBJECT_NAME = 'ChildData'
JOIN OBJECT_ENTRY oe
  ON pao.OBJECT_ID = oe.ID
JOIN OBJECT_VERSION ov
  ON oe.ID = ov.ENTRY_ID AND ov.VERSION = pao.VERSION
WHERE pal.ID = :log_id;
*/
