CREATE TABLE SB4DSSTRING (
	ID NUMERIC NOT NULL,
	VAL VARCHAR2(1000)  NULL
);
CREATE INDEX SB4DSSTRING_ID_IDX ON  SB4DSSTRING (ID);
CREATE INDEX SB4DSSTRING_VAL_IDX ON SB4DSSTRING (VAL);

CREATE TABLE SB4DSINT (
	ID NUMERIC NOT NULL,
	VAL NUMERIC NULL
);
CREATE INDEX SB4DSINT_ID_IDX ON  SB4DSINT (ID);
CREATE INDEX SB4DSINT_VAL_IDX ON SB4DSINT (VAL);
