/*
 * GeoMap api
 * The geomap api is resposible for the geomap components that shows a list of item. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.geomap.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.smartbit4all.api.geomap.bean.GeoMapItem;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GeoMapEditingSession
 */
@JsonPropertyOrder({
  GeoMapEditingSession.PENDING_ITEMS
})
@JsonTypeName("GeoMapEditingSession")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GeoMapEditingSession {
  public static final String PENDING_ITEMS = "pendingItems";
  private Map<String, List<GeoMapItem>> pendingItems = null;

  public GeoMapEditingSession() { 
  }

  public GeoMapEditingSession pendingItems(Map<String, List<GeoMapItem>> pendingItems) {
    
    this.pendingItems = pendingItems;
    return this;
  }

  public GeoMapEditingSession putPendingItemsItem(String key, List<GeoMapItem> pendingItemsItem) {
    if (this.pendingItems == null) {
      this.pendingItems = new HashMap<>();
    }
    this.pendingItems.put(key, pendingItemsItem);
    return this;
  }

   /**
   * Get pendingItems
   * @return pendingItems
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(PENDING_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<GeoMapItem>> getPendingItems() {
    return pendingItems;
  }


  @JsonProperty(PENDING_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingItems(Map<String, List<GeoMapItem>> pendingItems) {
    this.pendingItems = pendingItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoMapEditingSession geoMapEditingSession = (GeoMapEditingSession) o;
    return Objects.equals(this.pendingItems, geoMapEditingSession.pendingItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pendingItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoMapEditingSession {\n");
    sb.append("    pendingItems: ").append(toIndentedString(pendingItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

