/*
 * GeoMap api
 * The geomap api is resposible for the geomap components that shows a list of item. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.geomap.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.collection.bean.StoredCollectionDescriptor;
import org.smartbit4all.api.filterexpression.bean.FilterExpressionList;
import org.smartbit4all.api.geomap.bean.GeoMapDataLoadingMode;
import org.smartbit4all.api.geomap.bean.GeoMapDataSourceType;
import org.smartbit4all.api.geomap.bean.GeoMapItem;
import org.smartbit4all.api.geomap.bean.GeoMapItemKind;
import org.smartbit4all.api.invocation.bean.InvocationRequest;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GeoMapDataSourceDescriptor
 */
@JsonPropertyOrder({
  GeoMapDataSourceDescriptor.ID,
  GeoMapDataSourceDescriptor.TARGET_LAYER,
  GeoMapDataSourceDescriptor.SOURCE_TYPE,
  GeoMapDataSourceDescriptor.ITEM_KIND,
  GeoMapDataSourceDescriptor.LOADING_MODE,
  GeoMapDataSourceDescriptor.SOURCE_COLLECTION,
  GeoMapDataSourceDescriptor.PATH_TO_ID,
  GeoMapDataSourceDescriptor.PATH_TO_POSITION,
  GeoMapDataSourceDescriptor.PATH_TO_BOUNDS,
  GeoMapDataSourceDescriptor.PATH_TO_TITLE,
  GeoMapDataSourceDescriptor.PATH_TO_DESCRIPTION,
  GeoMapDataSourceDescriptor.INCLUDE_IF,
  GeoMapDataSourceDescriptor.INCLUSION_PREDICATE,
  GeoMapDataSourceDescriptor.SEARCH_INDEX_SCHEMA,
  GeoMapDataSourceDescriptor.SEARCH_INDEX_NAME,
  GeoMapDataSourceDescriptor.ID_COLUMN,
  GeoMapDataSourceDescriptor.TITLE_COLUMN,
  GeoMapDataSourceDescriptor.DESCRIPTION_COLUMN,
  GeoMapDataSourceDescriptor.LATITUDE_COLUMN,
  GeoMapDataSourceDescriptor.LONGITUDE_COLUMN,
  GeoMapDataSourceDescriptor.FILTER_EXPRESSION_LIST,
  GeoMapDataSourceDescriptor.INVOCATION_REQUEST,
  GeoMapDataSourceDescriptor.INLINE_ITEMS
})
@JsonTypeName("GeoMapDataSourceDescriptor")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GeoMapDataSourceDescriptor {
  public static final String ID = "id";
  private String id;

  public static final String TARGET_LAYER = "targetLayer";
  private String targetLayer;

  public static final String SOURCE_TYPE = "sourceType";
  private GeoMapDataSourceType sourceType;

  public static final String ITEM_KIND = "itemKind";
  private GeoMapItemKind itemKind;

  public static final String LOADING_MODE = "loadingMode";
  private GeoMapDataLoadingMode loadingMode;

  public static final String SOURCE_COLLECTION = "sourceCollection";
  private StoredCollectionDescriptor sourceCollection = null;

  public static final String PATH_TO_ID = "pathToId";
  private List<String> pathToId = null;

  public static final String PATH_TO_POSITION = "pathToPosition";
  private List<String> pathToPosition = null;

  public static final String PATH_TO_BOUNDS = "pathToBounds";
  private List<String> pathToBounds = null;

  public static final String PATH_TO_TITLE = "pathToTitle";
  private List<String> pathToTitle = null;

  public static final String PATH_TO_DESCRIPTION = "pathToDescription";
  private List<String> pathToDescription = null;

  public static final String INCLUDE_IF = "includeIf";
  private List<String> includeIf = null;

  public static final String INCLUSION_PREDICATE = "inclusionPredicate";
  private InvocationRequest inclusionPredicate = null;

  public static final String SEARCH_INDEX_SCHEMA = "searchIndexSchema";
  private String searchIndexSchema;

  public static final String SEARCH_INDEX_NAME = "searchIndexName";
  private String searchIndexName;

  public static final String ID_COLUMN = "idColumn";
  private String idColumn;

  public static final String TITLE_COLUMN = "titleColumn";
  private String titleColumn;

  public static final String DESCRIPTION_COLUMN = "descriptionColumn";
  private String descriptionColumn;

  public static final String LATITUDE_COLUMN = "latitudeColumn";
  private String latitudeColumn;

  public static final String LONGITUDE_COLUMN = "longitudeColumn";
  private String longitudeColumn;

  public static final String FILTER_EXPRESSION_LIST = "filterExpressionList";
  private FilterExpressionList filterExpressionList = null;

  public static final String INVOCATION_REQUEST = "invocationRequest";
  private InvocationRequest invocationRequest = null;

  public static final String INLINE_ITEMS = "inlineItems";
  private List<GeoMapItem> inlineItems = null;

  public GeoMapDataSourceDescriptor() { 
  }

  public GeoMapDataSourceDescriptor id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Uniquely identifies the the data source for a given map. May be retrieved from GeoMapApi if the data source needs to be modified after map creation. 
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Uniquely identifies the the data source for a given map. May be retrieved from GeoMapApi if the data source needs to be modified after map creation. ")
  @JsonProperty(ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GeoMapDataSourceDescriptor targetLayer(String targetLayer) {
    
    this.targetLayer = targetLayer;
    return this;
  }

   /**
   * Get targetLayer
   * @return targetLayer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(TARGET_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetLayer() {
    return targetLayer;
  }


  @JsonProperty(TARGET_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetLayer(String targetLayer) {
    this.targetLayer = targetLayer;
  }


  public GeoMapDataSourceDescriptor sourceType(GeoMapDataSourceType sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeoMapDataSourceType getSourceType() {
    return sourceType;
  }


  @JsonProperty(SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceType(GeoMapDataSourceType sourceType) {
    this.sourceType = sourceType;
  }


  public GeoMapDataSourceDescriptor itemKind(GeoMapItemKind itemKind) {
    
    this.itemKind = itemKind;
    return this;
  }

   /**
   * Get itemKind
   * @return itemKind
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(ITEM_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeoMapItemKind getItemKind() {
    return itemKind;
  }


  @JsonProperty(ITEM_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemKind(GeoMapItemKind itemKind) {
    this.itemKind = itemKind;
  }


  public GeoMapDataSourceDescriptor loadingMode(GeoMapDataLoadingMode loadingMode) {
    
    this.loadingMode = loadingMode;
    return this;
  }

   /**
   * Get loadingMode
   * @return loadingMode
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(LOADING_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeoMapDataLoadingMode getLoadingMode() {
    return loadingMode;
  }


  @JsonProperty(LOADING_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingMode(GeoMapDataLoadingMode loadingMode) {
    this.loadingMode = loadingMode;
  }


  public GeoMapDataSourceDescriptor sourceCollection(StoredCollectionDescriptor sourceCollection) {
    
    this.sourceCollection = sourceCollection;
    return this;
  }

   /**
   * Get sourceCollection
   * @return sourceCollection
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(SOURCE_COLLECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StoredCollectionDescriptor getSourceCollection() {
    return sourceCollection;
  }


  @JsonProperty(SOURCE_COLLECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceCollection(StoredCollectionDescriptor sourceCollection) {
    this.sourceCollection = sourceCollection;
  }


  public GeoMapDataSourceDescriptor pathToId(List<String> pathToId) {
    
    this.pathToId = pathToId;
    return this;
  }

  public GeoMapDataSourceDescriptor addPathToIdItem(String pathToIdItem) {
    if (this.pathToId == null) {
      this.pathToId = new ArrayList<>();
    }
    this.pathToId.add(pathToIdItem);
    return this;
  }

   /**
   * Get pathToId
   * @return pathToId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(PATH_TO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPathToId() {
    return pathToId;
  }


  @JsonProperty(PATH_TO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathToId(List<String> pathToId) {
    this.pathToId = pathToId;
  }


  public GeoMapDataSourceDescriptor pathToPosition(List<String> pathToPosition) {
    
    this.pathToPosition = pathToPosition;
    return this;
  }

  public GeoMapDataSourceDescriptor addPathToPositionItem(String pathToPositionItem) {
    if (this.pathToPosition == null) {
      this.pathToPosition = new ArrayList<>();
    }
    this.pathToPosition.add(pathToPositionItem);
    return this;
  }

   /**
   * Get pathToPosition
   * @return pathToPosition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(PATH_TO_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPathToPosition() {
    return pathToPosition;
  }


  @JsonProperty(PATH_TO_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathToPosition(List<String> pathToPosition) {
    this.pathToPosition = pathToPosition;
  }


  public GeoMapDataSourceDescriptor pathToBounds(List<String> pathToBounds) {
    
    this.pathToBounds = pathToBounds;
    return this;
  }

  public GeoMapDataSourceDescriptor addPathToBoundsItem(String pathToBoundsItem) {
    if (this.pathToBounds == null) {
      this.pathToBounds = new ArrayList<>();
    }
    this.pathToBounds.add(pathToBoundsItem);
    return this;
  }

   /**
   * Define what kind of item to create
   * @return pathToBounds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Define what kind of item to create")
  @JsonProperty(PATH_TO_BOUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPathToBounds() {
    return pathToBounds;
  }


  @JsonProperty(PATH_TO_BOUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathToBounds(List<String> pathToBounds) {
    this.pathToBounds = pathToBounds;
  }


  public GeoMapDataSourceDescriptor pathToTitle(List<String> pathToTitle) {
    
    this.pathToTitle = pathToTitle;
    return this;
  }

  public GeoMapDataSourceDescriptor addPathToTitleItem(String pathToTitleItem) {
    if (this.pathToTitle == null) {
      this.pathToTitle = new ArrayList<>();
    }
    this.pathToTitle.add(pathToTitleItem);
    return this;
  }

   /**
   * Get pathToTitle
   * @return pathToTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(PATH_TO_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPathToTitle() {
    return pathToTitle;
  }


  @JsonProperty(PATH_TO_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathToTitle(List<String> pathToTitle) {
    this.pathToTitle = pathToTitle;
  }


  public GeoMapDataSourceDescriptor pathToDescription(List<String> pathToDescription) {
    
    this.pathToDescription = pathToDescription;
    return this;
  }

  public GeoMapDataSourceDescriptor addPathToDescriptionItem(String pathToDescriptionItem) {
    if (this.pathToDescription == null) {
      this.pathToDescription = new ArrayList<>();
    }
    this.pathToDescription.add(pathToDescriptionItem);
    return this;
  }

   /**
   * Get pathToDescription
   * @return pathToDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(PATH_TO_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPathToDescription() {
    return pathToDescription;
  }


  @JsonProperty(PATH_TO_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathToDescription(List<String> pathToDescription) {
    this.pathToDescription = pathToDescription;
  }


  public GeoMapDataSourceDescriptor includeIf(List<String> includeIf) {
    
    this.includeIf = includeIf;
    return this;
  }

  public GeoMapDataSourceDescriptor addIncludeIfItem(String includeIfItem) {
    if (this.includeIf == null) {
      this.includeIf = new ArrayList<>();
    }
    this.includeIf.add(includeIfItem);
    return this;
  }

   /**
   * Get includeIf
   * @return includeIf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(INCLUDE_IF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIncludeIf() {
    return includeIf;
  }


  @JsonProperty(INCLUDE_IF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeIf(List<String> includeIf) {
    this.includeIf = includeIf;
  }


  public GeoMapDataSourceDescriptor inclusionPredicate(InvocationRequest inclusionPredicate) {
    
    this.inclusionPredicate = inclusionPredicate;
    return this;
  }

   /**
   * Get inclusionPredicate
   * @return inclusionPredicate
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(INCLUSION_PREDICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvocationRequest getInclusionPredicate() {
    return inclusionPredicate;
  }


  @JsonProperty(INCLUSION_PREDICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInclusionPredicate(InvocationRequest inclusionPredicate) {
    this.inclusionPredicate = inclusionPredicate;
  }


  public GeoMapDataSourceDescriptor searchIndexSchema(String searchIndexSchema) {
    
    this.searchIndexSchema = searchIndexSchema;
    return this;
  }

   /**
   * Get searchIndexSchema
   * @return searchIndexSchema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(SEARCH_INDEX_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSearchIndexSchema() {
    return searchIndexSchema;
  }


  @JsonProperty(SEARCH_INDEX_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchIndexSchema(String searchIndexSchema) {
    this.searchIndexSchema = searchIndexSchema;
  }


  public GeoMapDataSourceDescriptor searchIndexName(String searchIndexName) {
    
    this.searchIndexName = searchIndexName;
    return this;
  }

   /**
   * Get searchIndexName
   * @return searchIndexName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(SEARCH_INDEX_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSearchIndexName() {
    return searchIndexName;
  }


  @JsonProperty(SEARCH_INDEX_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchIndexName(String searchIndexName) {
    this.searchIndexName = searchIndexName;
  }


  public GeoMapDataSourceDescriptor idColumn(String idColumn) {
    
    this.idColumn = idColumn;
    return this;
  }

   /**
   * Get idColumn
   * @return idColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(ID_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdColumn() {
    return idColumn;
  }


  @JsonProperty(ID_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdColumn(String idColumn) {
    this.idColumn = idColumn;
  }


  public GeoMapDataSourceDescriptor titleColumn(String titleColumn) {
    
    this.titleColumn = titleColumn;
    return this;
  }

   /**
   * Get titleColumn
   * @return titleColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(TITLE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitleColumn() {
    return titleColumn;
  }


  @JsonProperty(TITLE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitleColumn(String titleColumn) {
    this.titleColumn = titleColumn;
  }


  public GeoMapDataSourceDescriptor descriptionColumn(String descriptionColumn) {
    
    this.descriptionColumn = descriptionColumn;
    return this;
  }

   /**
   * Get descriptionColumn
   * @return descriptionColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(DESCRIPTION_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescriptionColumn() {
    return descriptionColumn;
  }


  @JsonProperty(DESCRIPTION_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptionColumn(String descriptionColumn) {
    this.descriptionColumn = descriptionColumn;
  }


  public GeoMapDataSourceDescriptor latitudeColumn(String latitudeColumn) {
    
    this.latitudeColumn = latitudeColumn;
    return this;
  }

   /**
   * Get latitudeColumn
   * @return latitudeColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(LATITUDE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatitudeColumn() {
    return latitudeColumn;
  }


  @JsonProperty(LATITUDE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatitudeColumn(String latitudeColumn) {
    this.latitudeColumn = latitudeColumn;
  }


  public GeoMapDataSourceDescriptor longitudeColumn(String longitudeColumn) {
    
    this.longitudeColumn = longitudeColumn;
    return this;
  }

   /**
   * Get longitudeColumn
   * @return longitudeColumn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(LONGITUDE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLongitudeColumn() {
    return longitudeColumn;
  }


  @JsonProperty(LONGITUDE_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongitudeColumn(String longitudeColumn) {
    this.longitudeColumn = longitudeColumn;
  }


  public GeoMapDataSourceDescriptor filterExpressionList(FilterExpressionList filterExpressionList) {
    
    this.filterExpressionList = filterExpressionList;
    return this;
  }

   /**
   * Get filterExpressionList
   * @return filterExpressionList
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(FILTER_EXPRESSION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FilterExpressionList getFilterExpressionList() {
    return filterExpressionList;
  }


  @JsonProperty(FILTER_EXPRESSION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterExpressionList(FilterExpressionList filterExpressionList) {
    this.filterExpressionList = filterExpressionList;
  }


  public GeoMapDataSourceDescriptor invocationRequest(InvocationRequest invocationRequest) {
    
    this.invocationRequest = invocationRequest;
    return this;
  }

   /**
   * GeoMapViewport -&gt; List&lt;GeoMapItem&gt; 
   * @return invocationRequest
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "GeoMapViewport -> List<GeoMapItem> ")
  @JsonProperty(INVOCATION_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvocationRequest getInvocationRequest() {
    return invocationRequest;
  }


  @JsonProperty(INVOCATION_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvocationRequest(InvocationRequest invocationRequest) {
    this.invocationRequest = invocationRequest;
  }


  public GeoMapDataSourceDescriptor inlineItems(List<GeoMapItem> inlineItems) {
    
    this.inlineItems = inlineItems;
    return this;
  }

  public GeoMapDataSourceDescriptor addInlineItemsItem(GeoMapItem inlineItemsItem) {
    if (this.inlineItems == null) {
      this.inlineItems = new ArrayList<>();
    }
    this.inlineItems.add(inlineItemsItem);
    return this;
  }

   /**
   * Get inlineItems
   * @return inlineItems
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(INLINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GeoMapItem> getInlineItems() {
    return inlineItems;
  }


  @JsonProperty(INLINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInlineItems(List<GeoMapItem> inlineItems) {
    this.inlineItems = inlineItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoMapDataSourceDescriptor geoMapDataSourceDescriptor = (GeoMapDataSourceDescriptor) o;
    return Objects.equals(this.id, geoMapDataSourceDescriptor.id) &&
        Objects.equals(this.targetLayer, geoMapDataSourceDescriptor.targetLayer) &&
        Objects.equals(this.sourceType, geoMapDataSourceDescriptor.sourceType) &&
        Objects.equals(this.itemKind, geoMapDataSourceDescriptor.itemKind) &&
        Objects.equals(this.loadingMode, geoMapDataSourceDescriptor.loadingMode) &&
        Objects.equals(this.sourceCollection, geoMapDataSourceDescriptor.sourceCollection) &&
        Objects.equals(this.pathToId, geoMapDataSourceDescriptor.pathToId) &&
        Objects.equals(this.pathToPosition, geoMapDataSourceDescriptor.pathToPosition) &&
        Objects.equals(this.pathToBounds, geoMapDataSourceDescriptor.pathToBounds) &&
        Objects.equals(this.pathToTitle, geoMapDataSourceDescriptor.pathToTitle) &&
        Objects.equals(this.pathToDescription, geoMapDataSourceDescriptor.pathToDescription) &&
        Objects.equals(this.includeIf, geoMapDataSourceDescriptor.includeIf) &&
        Objects.equals(this.inclusionPredicate, geoMapDataSourceDescriptor.inclusionPredicate) &&
        Objects.equals(this.searchIndexSchema, geoMapDataSourceDescriptor.searchIndexSchema) &&
        Objects.equals(this.searchIndexName, geoMapDataSourceDescriptor.searchIndexName) &&
        Objects.equals(this.idColumn, geoMapDataSourceDescriptor.idColumn) &&
        Objects.equals(this.titleColumn, geoMapDataSourceDescriptor.titleColumn) &&
        Objects.equals(this.descriptionColumn, geoMapDataSourceDescriptor.descriptionColumn) &&
        Objects.equals(this.latitudeColumn, geoMapDataSourceDescriptor.latitudeColumn) &&
        Objects.equals(this.longitudeColumn, geoMapDataSourceDescriptor.longitudeColumn) &&
        Objects.equals(this.filterExpressionList, geoMapDataSourceDescriptor.filterExpressionList) &&
        Objects.equals(this.invocationRequest, geoMapDataSourceDescriptor.invocationRequest) &&
        Objects.equals(this.inlineItems, geoMapDataSourceDescriptor.inlineItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, targetLayer, sourceType, itemKind, loadingMode, sourceCollection, pathToId, pathToPosition, pathToBounds, pathToTitle, pathToDescription, includeIf, inclusionPredicate, searchIndexSchema, searchIndexName, idColumn, titleColumn, descriptionColumn, latitudeColumn, longitudeColumn, filterExpressionList, invocationRequest, inlineItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoMapDataSourceDescriptor {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    targetLayer: ").append(toIndentedString(targetLayer)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    itemKind: ").append(toIndentedString(itemKind)).append("\n");
    sb.append("    loadingMode: ").append(toIndentedString(loadingMode)).append("\n");
    sb.append("    sourceCollection: ").append(toIndentedString(sourceCollection)).append("\n");
    sb.append("    pathToId: ").append(toIndentedString(pathToId)).append("\n");
    sb.append("    pathToPosition: ").append(toIndentedString(pathToPosition)).append("\n");
    sb.append("    pathToBounds: ").append(toIndentedString(pathToBounds)).append("\n");
    sb.append("    pathToTitle: ").append(toIndentedString(pathToTitle)).append("\n");
    sb.append("    pathToDescription: ").append(toIndentedString(pathToDescription)).append("\n");
    sb.append("    includeIf: ").append(toIndentedString(includeIf)).append("\n");
    sb.append("    inclusionPredicate: ").append(toIndentedString(inclusionPredicate)).append("\n");
    sb.append("    searchIndexSchema: ").append(toIndentedString(searchIndexSchema)).append("\n");
    sb.append("    searchIndexName: ").append(toIndentedString(searchIndexName)).append("\n");
    sb.append("    idColumn: ").append(toIndentedString(idColumn)).append("\n");
    sb.append("    titleColumn: ").append(toIndentedString(titleColumn)).append("\n");
    sb.append("    descriptionColumn: ").append(toIndentedString(descriptionColumn)).append("\n");
    sb.append("    latitudeColumn: ").append(toIndentedString(latitudeColumn)).append("\n");
    sb.append("    longitudeColumn: ").append(toIndentedString(longitudeColumn)).append("\n");
    sb.append("    filterExpressionList: ").append(toIndentedString(filterExpressionList)).append("\n");
    sb.append("    invocationRequest: ").append(toIndentedString(invocationRequest)).append("\n");
    sb.append("    inlineItems: ").append(toIndentedString(inlineItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

