openapi: 3.0.1
info:
  title: Attachment grid api
  description: Attachment grid api.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: AttachmentGrid
paths: {}
components:
  schemas:
    AttachmentGridDescriptor:
      type: object
      description: Describes an attachment grid, made up of BinaryContentDatas.
      properties:
        attachmentList:
          type: array
          items:
            type: BinaryContentData
        gridWidgetId:
          type: string
        viewUuid:
          type: string
          format: uuid
        logicalSchema:
          type: string
        saveRequest:
          type: InvocationRequest
        searchIndex:
          type: SearchIndexDescriptor
        additionalActions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalAttachmentAction'
        saveButtonDescriptor:
          $ref: '#/components/schemas/ButtonDescriptor'
        uploadButtonDescriptor:
          $ref: '#/components/schemas/ButtonDescriptor'
        refreshButtonDescriptor:
          $ref: '#/components/schemas/ButtonDescriptor'
        options:
          $ref: '#/components/schemas/AttachmentGridOptions'
        columns:
          type: array
          items:
            type: string

    ButtonDescriptor:
      type: object
      properties:
        toolbar:
          type: string
        identifier:
          type: string
        params:
          type: object
          additionalProperties:
            type: object
        descriptor:
          type: UiActionDescriptor

    AdditionalAttachmentAction:
      type: object
      description: Describes an additional action, for the attachment grid.
      properties:
        code:
          type: string
          description: 'The title of the action.'
        descriptor:
          type: UiActionDescriptor
        actionInvocationRequest:
          description: 'The additional action itself'
          type: InvocationRequest
    AttachmentGridOptions:
      type: object
      properties:
        isPreviewable:
          type: boolean
          default: true
        isDownloadable:
          type: boolean
          default: true
        isEditable:
          type: boolean
          default: true
        closeOnSave:
          type: boolean
          default: false
        autoSave:
          type: boolean
          default: false
        isMultipleInput:
          type: boolean
          default: true
        dialogTitle:
          description: The title of the dialog, only used with dialog type.
          type: string
        useIconActions:
          type: boolean
          default: false
        toolbarPosition:
          $ref: '#/components/schemas/ToolbarPosition'

    ToolbarPosition:
      enum: [ABOVE, HEADER]
