openapi: 3.0.1
info:
  title: Subject selector api
  description: Subject selector ui api.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: SubjectSelector
paths: {}
components:
  schemas:
    SubjectSelectorPageModel:
      type: object
      properties:
        selection:
          type: string
    UserSelectorPageModel:
      type: object
      properties:
        selection:
          type: string
    AclPageConfig:
      type: object
      required: [gridConfigs]
      properties:
        subjectModel:
          type: string
        selectorViewName:
          type: string
        selectionCallback:
          type: InvocationRequest
        gridConfigs:
          type: array
          items:
            $ref: '#/components/schemas/AclGridConfig'
    AclGridConfig:
      type: object
      required: [subjectTypes]
      properties:
        aclModel:
          type: string
        aclName:
          type: string
        operation:
          type: string
        selectionMode:
          type: GridSelectionMode
        mandatory:
          type: boolean
        subjectTypes:
          type: array
          items:
            type: string
    AclGridItem:
      type: object
      properties:
        subject:
          type: Subject
        name:
          type: string
        comment:
          type: string
