openapi: 3.0.1
info:
  title: Subject selector api
  description: Subject selector ui api.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: SubjectSelector
paths: {}
components:
  schemas:
    SubjectSelectorPageModel:
      type: object
      properties:
        selection:
          type: string
    UserSelectorPageModel:
      type: object
      properties:
        selection:
          type: string
    AclPageConfig:
      type: object
      required: [gridConfigs]
      properties:
        aclObjectUriParam:
          type: string
        subjectModel:
          type: string
        subjectSelectorViewName:
          type: string
        userSelectorViewName:
          type: string
        selectionCallback:
          type: InvocationRequest
        gridConfigs:
          type: array
          items:
            $ref: '#/components/schemas/AclGridConfig'
        saveDirectly:
          description: |
            If true then changes to ACLObject will be saved on user action, implicitly. If false, 
            original ACLObject is handled in a view variable and can be saved explicitly.
          type: boolean
          default: true
    AclGridConfig:
      type: object
      required: [subjectTypes,subjectValues]
      properties:
        gridId:
          description: If necessary, we can specify explicit gridId, otherwise aclName will be used.
          type: string
        aclModel:
          type: string
        aclName:
          type: string
        operation:
          type: string
        selectionMode:
          type: GridSelectionMode
        mandatory:
          type: boolean
        subjectTypes:
          type: array
          items:
            type: string
        searchPageConfig:
          type: SearchPageConfig
        selectionType:
          enum: [SUBJECT,USER]
        subjectValues:
          type: array
          items:
            type: Subject
        minNoOfRows:
          type: integer
          format: int64
        maxNoOfRows:
          type: integer
          format: int64
        hasComment:
          type: boolean
        addEnabled:
          type: boolean
          default: true
        deleteEnabled:
          type: boolean
          default: true
    AclGridItem:
      type: object
      properties:
        subject:
          type: Subject
        name:
          type: string
        comment:
          type: string
