openapi: 3.0.1
info:
  title: Subject selector api
  description: Subject selector ui api.
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: SubjectSelector
paths: {}
components:
  schemas:
    SubjectSelectorPageModel:
      type: object
      properties:
        selectedDescriptor:
          type: string
