/*
 * MasterDataManagement api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.mdm.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.net.URI;
import org.smartbit4all.api.mdm.bean.MDMEntryChangeOperation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * The change item defines the operation and refers to the related versioned uris of the chnaged object. 
 */
@Schema(description = "The change item defines the operation and refers to the related versioned uris of the chnaged object. ")
@JsonPropertyOrder({
  MDMEntryChangeItem.OPERATION,
  MDMEntryChangeItem.URI,
  MDMEntryChangeItem.PREV_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class MDMEntryChangeItem {
  public static final String OPERATION = "operation";
  private MDMEntryChangeOperation operation;

  public static final String URI = "uri";
  private URI uri;

  public static final String PREV_URI = "prevUri";
  private URI prevUri;

  public MDMEntryChangeItem() {
  }

  public MDMEntryChangeItem operation(MDMEntryChangeOperation operation) {
    
    this.operation = operation;
    return this;
  }

  /**
   * Get operation
   * @return operation
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  @JsonProperty(OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MDMEntryChangeOperation getOperation() {
    return operation;
  }


  @JsonProperty(OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperation(MDMEntryChangeOperation operation) {
    this.operation = operation;
  }

  public MDMEntryChangeItem uri(URI uri) {
    
    this.uri = uri;
    return this;
  }

  /**
   * The uri refers to the actual state of the new or changed object. It is versioned object uri points to the exact version of the object. 
   * @return uri
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The uri refers to the actual state of the new or changed object. It is versioned object uri points to the exact version of the object. ")
  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUri() {
    return uri;
  }


  @JsonProperty(URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(URI uri) {
    this.uri = uri;
  }

  public MDMEntryChangeItem prevUri(URI prevUri) {
    
    this.prevUri = prevUri;
    return this;
  }

  /**
   * The uri refers to the previous state of the new or changed object. Set only in case of change.
   * @return prevUri
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The uri refers to the previous state of the new or changed object. Set only in case of change.")
  @JsonProperty(PREV_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getPrevUri() {
    return prevUri;
  }


  @JsonProperty(PREV_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrevUri(URI prevUri) {
    this.prevUri = prevUri;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MDMEntryChangeItem mdMEntryChangeItem = (MDMEntryChangeItem) o;
    return Objects.equals(this.operation, mdMEntryChangeItem.operation) &&
        Objects.equals(this.uri, mdMEntryChangeItem.uri) &&
        Objects.equals(this.prevUri, mdMEntryChangeItem.prevUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, uri, prevUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MDMEntryChangeItem {\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    prevUri: ").append(toIndentedString(prevUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

