/*
 * MasterDataManagement api
 * null
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.mdm.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.mdm.bean.MDMEntryChangeItem;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The entry change contains all the changeed items of an MDMEntry. 
 */
@ApiModel(description = "The entry change contains all the changeed items of an MDMEntry. ")
@JsonPropertyOrder({
  MDMEntryChange.ENTRY,
  MDMEntryChange.ITEMS
})
@JsonTypeName("MDMEntryChange")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MDMEntryChange {
  public static final String ENTRY = "entry";
  private String entry;

  public static final String ITEMS = "items";
  private List<MDMEntryChangeItem> items = new ArrayList<>();

  public MDMEntryChange() { 
  }

  public MDMEntryChange entry(String entry) {
    
    this.entry = entry;
    return this;
  }

   /**
   * The name of the entry
   * @return entry
  **/
  @javax.annotation.Nonnull
  @NotNull
  @ApiModelProperty(required = true, value = "The name of the entry")
  @JsonProperty(ENTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntry() {
    return entry;
  }


  @JsonProperty(ENTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntry(String entry) {
    this.entry = entry;
  }


  public MDMEntryChange items(List<MDMEntryChangeItem> items) {
    
    this.items = items;
    return this;
  }

  public MDMEntryChange addItemsItem(MDMEntryChangeItem itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * The chnages items of the entry.
   * @return items
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "The chnages items of the entry.")
  @JsonProperty(ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<MDMEntryChangeItem> getItems() {
    return items;
  }


  @JsonProperty(ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(List<MDMEntryChangeItem> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MDMEntryChange mdMEntryChange = (MDMEntryChange) o;
    return Objects.equals(this.entry, mdMEntryChange.entry) &&
        Objects.equals(this.items, mdMEntryChange.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entry, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MDMEntryChange {\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

