/*
 * MasterDataManagement api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.mdm.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * MDMSetupEntry
 */
@JsonPropertyOrder({
  MDMSetupEntry.DEFINITION,
  MDMSetupEntry.ENTRY,
  MDMSetupEntry.UNIQUE_PATH,
  MDMSetupEntry.ENTRIES,
  MDMSetupEntry.TYPE_CLASS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class MDMSetupEntry {
  public static final String DEFINITION = "definition";
  private String definition;

  public static final String ENTRY = "entry";
  private String entry;

  public static final String UNIQUE_PATH = "uniquePath";
  private List<String> uniquePath = new ArrayList<>();

  public static final String ENTRIES = "entries";
  private List<Map<String, Object>> entries = new ArrayList<>();

  public static final String TYPE_CLASS = "typeClass";
  private String typeClass;

  public MDMSetupEntry() {
  }

  public MDMSetupEntry definition(String definition) {
    
    this.definition = definition;
    return this;
  }

  /**
   * Get definition
   * @return definition
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefinition() {
    return definition;
  }


  @JsonProperty(DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefinition(String definition) {
    this.definition = definition;
  }

  public MDMSetupEntry entry(String entry) {
    
    this.entry = entry;
    return this;
  }

  /**
   * Get entry
   * @return entry
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntry() {
    return entry;
  }


  @JsonProperty(ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntry(String entry) {
    this.entry = entry;
  }

  public MDMSetupEntry uniquePath(List<String> uniquePath) {
    
    this.uniquePath = uniquePath;
    return this;
  }

  public MDMSetupEntry addUniquePathItem(String uniquePathItem) {
    if (this.uniquePath == null) {
      this.uniquePath = new ArrayList<>();
    }
    this.uniquePath.add(uniquePathItem);
    return this;
  }

  /**
   * Get uniquePath
   * @return uniquePath
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(UNIQUE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getUniquePath() {
    return uniquePath;
  }


  @JsonProperty(UNIQUE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUniquePath(List<String> uniquePath) {
    this.uniquePath = uniquePath;
  }

  public MDMSetupEntry entries(List<Map<String, Object>> entries) {
    
    this.entries = entries;
    return this;
  }

  public MDMSetupEntry addEntriesItem(Map<String, Object> entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

  /**
   * Get entries
   * @return entries
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Map<String, Object>> getEntries() {
    return entries;
  }


  @JsonProperty(ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntries(List<Map<String, Object>> entries) {
    this.entries = entries;
  }

  public MDMSetupEntry typeClass(String typeClass) {
    
    this.typeClass = typeClass;
    return this;
  }

  /**
   * Get typeClass
   * @return typeClass
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(TYPE_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeClass() {
    return typeClass;
  }


  @JsonProperty(TYPE_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeClass(String typeClass) {
    this.typeClass = typeClass;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MDMSetupEntry mdMSetupEntry = (MDMSetupEntry) o;
    return Objects.equals(this.definition, mdMSetupEntry.definition) &&
        Objects.equals(this.entry, mdMSetupEntry.entry) &&
        Objects.equals(this.uniquePath, mdMSetupEntry.uniquePath) &&
        Objects.equals(this.entries, mdMSetupEntry.entries) &&
        Objects.equals(this.typeClass, mdMSetupEntry.typeClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definition, entry, uniquePath, entries, typeClass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MDMSetupEntry {\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("    uniquePath: ").append(toIndentedString(uniquePath)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    typeClass: ").append(toIndentedString(typeClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

