/*
 * MasterDataManagement api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.mdm.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.smartbit4all.api.collection.bean.VectorCollectionDescriptor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * MDMValueSetSetupEntry
 */
@JsonPropertyOrder({
  MDMValueSetSetupEntry.DEFINITION,
  MDMValueSetSetupEntry.NAME,
  MDMValueSetSetupEntry.CODE,
  MDMValueSetSetupEntry.VECTOR_COLLECTION,
  MDMValueSetSetupEntry.IMPORTABLE,
  MDMValueSetSetupEntry.CSV_SEPARATOR,
  MDMValueSetSetupEntry.DISPLAYED_COLUMNS,
  MDMValueSetSetupEntry.FULL_CSV_PATH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class MDMValueSetSetupEntry {
  public static final String DEFINITION = "definition";
  private String definition;

  public static final String NAME = "name";
  private String name;

  public static final String CODE = "code";
  private String code;

  public static final String VECTOR_COLLECTION = "vectorCollection";
  private VectorCollectionDescriptor vectorCollection = null;

  public static final String IMPORTABLE = "importable";
  private Boolean importable;

  public static final String CSV_SEPARATOR = "csvSeparator";
  private String csvSeparator;

  public static final String DISPLAYED_COLUMNS = "displayedColumns";
  private List<String> displayedColumns = new ArrayList<>();

  public static final String FULL_CSV_PATH = "fullCsvPath";
  private String fullCsvPath;

  public MDMValueSetSetupEntry() {
  }

  public MDMValueSetSetupEntry definition(String definition) {
    
    this.definition = definition;
    return this;
  }

  /**
   * Get definition
   * @return definition
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefinition() {
    return definition;
  }


  @JsonProperty(DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefinition(String definition) {
    this.definition = definition;
  }

  public MDMValueSetSetupEntry name(String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public MDMValueSetSetupEntry code(String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }

  public MDMValueSetSetupEntry vectorCollection(VectorCollectionDescriptor vectorCollection) {
    
    this.vectorCollection = vectorCollection;
    return this;
  }

  /**
   * Get vectorCollection
   * @return vectorCollection
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(VECTOR_COLLECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VectorCollectionDescriptor getVectorCollection() {
    return vectorCollection;
  }


  @JsonProperty(VECTOR_COLLECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVectorCollection(VectorCollectionDescriptor vectorCollection) {
    this.vectorCollection = vectorCollection;
  }

  public MDMValueSetSetupEntry importable(Boolean importable) {
    
    this.importable = importable;
    return this;
  }

  /**
   * Get importable
   * @return importable
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(IMPORTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getImportable() {
    return importable;
  }


  @JsonProperty(IMPORTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImportable(Boolean importable) {
    this.importable = importable;
  }

  public MDMValueSetSetupEntry csvSeparator(String csvSeparator) {
    
    this.csvSeparator = csvSeparator;
    return this;
  }

  /**
   * Get csvSeparator
   * @return csvSeparator
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(CSV_SEPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCsvSeparator() {
    return csvSeparator;
  }


  @JsonProperty(CSV_SEPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCsvSeparator(String csvSeparator) {
    this.csvSeparator = csvSeparator;
  }

  public MDMValueSetSetupEntry displayedColumns(List<String> displayedColumns) {
    
    this.displayedColumns = displayedColumns;
    return this;
  }

  public MDMValueSetSetupEntry addDisplayedColumnsItem(String displayedColumnsItem) {
    if (this.displayedColumns == null) {
      this.displayedColumns = new ArrayList<>();
    }
    this.displayedColumns.add(displayedColumnsItem);
    return this;
  }

  /**
   * Get displayedColumns
   * @return displayedColumns
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(DISPLAYED_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDisplayedColumns() {
    return displayedColumns;
  }


  @JsonProperty(DISPLAYED_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayedColumns(List<String> displayedColumns) {
    this.displayedColumns = displayedColumns;
  }

  public MDMValueSetSetupEntry fullCsvPath(String fullCsvPath) {
    
    this.fullCsvPath = fullCsvPath;
    return this;
  }

  /**
   * Get fullCsvPath
   * @return fullCsvPath
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(FULL_CSV_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullCsvPath() {
    return fullCsvPath;
  }


  @JsonProperty(FULL_CSV_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullCsvPath(String fullCsvPath) {
    this.fullCsvPath = fullCsvPath;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MDMValueSetSetupEntry mdMValueSetSetupEntry = (MDMValueSetSetupEntry) o;
    return Objects.equals(this.definition, mdMValueSetSetupEntry.definition) &&
        Objects.equals(this.name, mdMValueSetSetupEntry.name) &&
        Objects.equals(this.code, mdMValueSetSetupEntry.code) &&
        Objects.equals(this.vectorCollection, mdMValueSetSetupEntry.vectorCollection) &&
        Objects.equals(this.importable, mdMValueSetSetupEntry.importable) &&
        Objects.equals(this.csvSeparator, mdMValueSetSetupEntry.csvSeparator) &&
        Objects.equals(this.displayedColumns, mdMValueSetSetupEntry.displayedColumns) &&
        Objects.equals(this.fullCsvPath, mdMValueSetSetupEntry.fullCsvPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definition, name, code, vectorCollection, importable, csvSeparator, displayedColumns, fullCsvPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MDMValueSetSetupEntry {\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    vectorCollection: ").append(toIndentedString(vectorCollection)).append("\n");
    sb.append("    importable: ").append(toIndentedString(importable)).append("\n");
    sb.append("    csvSeparator: ").append(toIndentedString(csvSeparator)).append("\n");
    sb.append("    displayedColumns: ").append(toIndentedString(displayedColumns)).append("\n");
    sb.append("    fullCsvPath: ").append(toIndentedString(fullCsvPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

