openapi: 3.0.1
info:
  title: Filter API
  description: Filter API
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: filter
    description: filter
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        '200':
          description: nope
components:
  schemas:
    FilterConfigMode:
      type: string
      enum: [static, simple_dynamic, dynamic]
    FilterConfig:
      type: object
      properties:
        filterFieldMetas:
          type: array
          items:
            $ref: '#/components/schemas/FilterFieldMeta'
        filterGroupMetas:
          type: array
          items:
            $ref: '#/components/schemas/FilterGroupMeta'
        defaultFilterStyle:
          type: string
        defaultFilterGroupStyle:
          type: string
    FilterFieldMeta:
      type: object
      description: "Descriptor of a possible filter field. This field doesn't have to correspond to an existing entity's property, it is simple a way of filtering."
      properties:
        name:
          type: string
          description: 'Name of the filterable field.'
        groupName:
          type: string
        style:
          type: string
        operations:
          type: array
          items:
            $ref: '#/components/schemas/FilterOperation'
    FilterGroupMeta:
      type: object
      properties:
        name:
          type: string
        icon:
          type: string
        style:
          type: string
        type:
          $ref: '#/components/schemas/FilterGroupType'
    FilterOperation:
      type: object
      description: 'Defines a possible way of using a filter field. For example: exact match, like, sounds like, interval, etc.'
      properties:
        filterView:
          type: string
          description: 'Declarative name of a FilterOperationUI, which will handle this operation.'
        field1:
          type: string
        field2:
          type: string
        possibleValues:
          type: string
          format: uri
        code:
          type: string
        displayValue:
          type: string
        icon:
          type: string
    FilterGroupType:
      type: string
      enum: [
          AND, OR
        ]
    FilterGroup:
      type: object
      description: 'AND / OR group of filters / groups.'
      properties:
        name:
          type: string
          description: Name of the group.
        type:
          $ref: '#/components/schemas/FilterGroupType'
        filterFields:
          type: array
          items:
            $ref: '#/components/schemas/FilterField'
        filterGroups:
          type: array
          items:
            $ref: '#/components/schemas/FilterGroup'
        isNegated:
          type: boolean
    FilterField:
      type: object
      properties:
        metaName:
          type: string
          description: Name of the referenced FilterFieldMeta.
        operation:
          $ref: '#/components/schemas/FilterOperation'
        value1:
          type: string
        value2:
          type: string
        selectedValues:
          type: array
          items:
            type: string
            format: uri
            #$ref: 'value-api.yaml#/components/schemas/Value'
