openapi: 3.0.1
info:
  title: value api
  description: value api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Value
paths:
  /possibleValues/{objectUri}:
    get:
      tags:
      - Value
      summary: Returns the possible value set for the given URI
      operationId: 'possibleValues'
      parameters: 
        - in: path
          name: objectUri
          schema:
            type: string
          required: true
          description: 'The URI of the field the possible values are requested for'
      responses:
        '200':
          description: 'The requested possible values'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Value'
components:
  schemas:
    Value:
      type: object
      required: [objectUri, displayValue]
      properties:
        objectUri:
          type: string
          format: uri
          description: 'The uri the object of the value can be accessed.'
        displayValue: 
          type: string
          description: 'The string value that can be shown on ui. It might be a label code or the exact label.'
        iconCode:
          type: string
          description: 'The code of icon that can be associatied with the value. It may be a uri.'