openapi: 3.0.1
info:
  title: value api
  description: value api
  termsOfService: ''
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
- name: Value
paths:
  /possibleValues/{fieldUri}:
    get:
      tags:
      - Value
      summary: Returns the possible value set for the given URI
      operationId: 'possibleValues'
      parameters: 
        - in: path
          name: fieldUri
          schema:
            type: string
            format: uri
          required: true
          description: 'The URI of the field the possible values are requested for'
      responses:
        '200':
          description: 'The requested possible values'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Value'
components:
  schemas:
    Value:
      type: object
      required: [code, value]
      properties:
        code:
          type: string
          description: 'The code the value can be referenced by'
        value: 
          type: string
          description: 'The string value of the literal'
        typeQName:
          type: string
          description: 'The qualified name of the type of the value'
        iconCode:
          type: string
          description: 'The code of icon that can be associatied with the value. It may be a uri.'