--
--    A -> B -> C -> F
--				^
--				\--- D -> E

CREATE TABLE A (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "AF1" VARCHAR2(255) NULL,
  "AF2" VARCHAR2(255) NULL,
  "B_ID" NUMBER(19) NULL
);

CREATE TABLE B (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "BF1" VARCHAR2(255) NULL,
  "BF2" VARCHAR2(255) NULL,
  "C_ID" NUMBER(19) NULL
);

CREATE TABLE C (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "CF1" VARCHAR2(255) NULL,
  "CF2" VARCHAR2(255) NULL,
  "CF3" VARCHAR2(255) NULL,
  "F_ID" NUMBER(19) NULL
);

CREATE TABLE D (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "DF1" VARCHAR2(255) NULL,
  "DF2" VARCHAR2(255) NULL,
  "E_ID" NUMBER(19) NULL,
  "C_ID" NUMBER(19) NULL
);

CREATE TABLE E (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "EF1" VARCHAR2(255) NULL,
  "EF2" VARCHAR2(255) NULL
);

CREATE TABLE F (
  "ID" NUMBER(19) NOT NULL, 
  "UID" VARCHAR2(255) NOT NULL,
  "FF1" VARCHAR2(255) NULL,
  "FF2" VARCHAR2(255) NULL
);

-- ids
ALTER TABLE A ADD CONSTRAINT SYS_A PRIMARY KEY (ID);
ALTER TABLE B ADD CONSTRAINT SYS_B PRIMARY KEY (ID);
ALTER TABLE C ADD CONSTRAINT SYS_C PRIMARY KEY (ID);
ALTER TABLE D ADD CONSTRAINT SYS_D PRIMARY KEY (ID);
ALTER TABLE E ADD CONSTRAINT SYS_E PRIMARY KEY (ID);
ALTER TABLE F ADD CONSTRAINT SYS_F PRIMARY KEY (ID);

-- fk indexes
CREATE INDEX A_B_ID_IDX ON A (B_ID);
CREATE INDEX B_C_ID_IDX ON B (C_ID);
CREATE INDEX C_F_ID_IDX ON C (F_ID);
CREATE INDEX D_C_ID_IDX ON D (C_ID);
CREATE INDEX D_E_ID_IDX ON D (E_ID);
