/*
 * Subject selector api
 * Subject selector ui api.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.bff.api.subjectselector.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.smartbit4all.api.filterexpression.bean.SearchPageConfig;
import org.smartbit4all.api.grid.bean.GridSelectionMode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * SubjectGridConfig
 */
@JsonPropertyOrder({
  SubjectGridConfig.GRID_ID,
  SubjectGridConfig.SELECTION_MODE,
  SubjectGridConfig.SUBJECT_TYPE,
  SubjectGridConfig.SEARCH_PAGE_CONFIG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class SubjectGridConfig {
  public static final String GRID_ID = "gridId";
  private String gridId;

  public static final String SELECTION_MODE = "selectionMode";
  private GridSelectionMode selectionMode = null;

  public static final String SUBJECT_TYPE = "subjectType";
  private String subjectType;

  public static final String SEARCH_PAGE_CONFIG = "searchPageConfig";
  private SearchPageConfig searchPageConfig = null;

  public SubjectGridConfig() {
  }

  public SubjectGridConfig gridId(String gridId) {
    
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(GRID_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGridId() {
    return gridId;
  }


  @JsonProperty(GRID_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGridId(String gridId) {
    this.gridId = gridId;
  }

  public SubjectGridConfig selectionMode(GridSelectionMode selectionMode) {
    
    this.selectionMode = selectionMode;
    return this;
  }

  /**
   * Get selectionMode
   * @return selectionMode
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(SELECTION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GridSelectionMode getSelectionMode() {
    return selectionMode;
  }


  @JsonProperty(SELECTION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelectionMode(GridSelectionMode selectionMode) {
    this.selectionMode = selectionMode;
  }

  public SubjectGridConfig subjectType(String subjectType) {
    
    this.subjectType = subjectType;
    return this;
  }

  /**
   * Get subjectType
   * @return subjectType
   */
  @jakarta.annotation.Nullable

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(SUBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubjectType() {
    return subjectType;
  }


  @JsonProperty(SUBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectType(String subjectType) {
    this.subjectType = subjectType;
  }

  public SubjectGridConfig searchPageConfig(SearchPageConfig searchPageConfig) {
    
    this.searchPageConfig = searchPageConfig;
    return this;
  }

  /**
   * Get searchPageConfig
   * @return searchPageConfig
   */
  @jakarta.annotation.Nullable
  @Valid

  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(SEARCH_PAGE_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SearchPageConfig getSearchPageConfig() {
    return searchPageConfig;
  }


  @JsonProperty(SEARCH_PAGE_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchPageConfig(SearchPageConfig searchPageConfig) {
    this.searchPageConfig = searchPageConfig;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectGridConfig subjectGridConfig = (SubjectGridConfig) o;
    return Objects.equals(this.gridId, subjectGridConfig.gridId) &&
        Objects.equals(this.selectionMode, subjectGridConfig.selectionMode) &&
        Objects.equals(this.subjectType, subjectGridConfig.subjectType) &&
        Objects.equals(this.searchPageConfig, subjectGridConfig.searchPageConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, selectionMode, subjectType, searchPageConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectGridConfig {\n");
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    selectionMode: ").append(toIndentedString(selectionMode)).append("\n");
    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    searchPageConfig: ").append(toIndentedString(searchPageConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

