/*
 * value api
 * value api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.value.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.smartbit4all.api.invocation.bean.InvocationRequest;
import org.smartbit4all.api.value.bean.ValueTransformationKind;
import org.smartbit4all.api.value.bean.ValueTransformationMappingItem;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * This object is a configuration to define the transformation from an input value set to an output value set. The transformation could be value mapping when the list of the values from the input are mapped one by one to the output values. This object is managed as a MDM entry in the platform. The ValueTransformationApi is using this MDM entry by default. If manage it by MDM then we enapsulate this object into a ValueTransformationConfig. 
 */
@JsonPropertyOrder({
  ValueTransformationConfigData.NAME,
  ValueTransformationConfigData.KIND,
  ValueTransformationConfigData.MAPPINGS,
  ValueTransformationConfigData.MDM_DEFINITION,
  ValueTransformationConfigData.MDM_ENTRY,
  ValueTransformationConfigData.MDM_PROPERTY_NAME,
  ValueTransformationConfigData.TRANSFORMATION
})
@JsonTypeName("ValueTransformationConfigData")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class ValueTransformationConfigData {
  public static final String NAME = "name";
  private String name;

  public static final String KIND = "kind";
  private ValueTransformationKind kind;

  public static final String MAPPINGS = "mappings";
  private List<@Valid ValueTransformationMappingItem> mappings = new ArrayList<>();

  public static final String MDM_DEFINITION = "mdmDefinition";
  private String mdmDefinition;

  public static final String MDM_ENTRY = "mdmEntry";
  private String mdmEntry;

  public static final String MDM_PROPERTY_NAME = "mdmPropertyName";
  private String mdmPropertyName;

  public static final String TRANSFORMATION = "transformation";
  private InvocationRequest transformation = null;

  public ValueTransformationConfigData() { 
  }

  public ValueTransformationConfigData name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The unique name of the transformation configuration. It matters only if it is managed by MDM.
   * @return name
  **/
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ValueTransformationConfigData kind(ValueTransformationKind kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValueTransformationKind getKind() {
    return kind;
  }


  @JsonProperty(KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(ValueTransformationKind kind) {
    this.kind = kind;
  }


  public ValueTransformationConfigData mappings(List<@Valid ValueTransformationMappingItem> mappings) {
    
    this.mappings = mappings;
    return this;
  }

  public ValueTransformationConfigData addMappingsItem(ValueTransformationMappingItem mappingsItem) {
    this.mappings.add(mappingsItem);
    return this;
  }

   /**
   * Get mappings
   * @return mappings
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(MAPPINGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<@Valid ValueTransformationMappingItem> getMappings() {
    return mappings;
  }


  @JsonProperty(MAPPINGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMappings(List<@Valid ValueTransformationMappingItem> mappings) {
    this.mappings = mappings;
  }


  public ValueTransformationConfigData mdmDefinition(String mdmDefinition) {
    
    this.mdmDefinition = mdmDefinition;
    return this;
  }

   /**
   * If the kind is a resolution by MDM entry then this is the name of MDM definition.
   * @return mdmDefinition
  **/
  @javax.annotation.Nullable

  @JsonProperty(MDM_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMdmDefinition() {
    return mdmDefinition;
  }


  @JsonProperty(MDM_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMdmDefinition(String mdmDefinition) {
    this.mdmDefinition = mdmDefinition;
  }


  public ValueTransformationConfigData mdmEntry(String mdmEntry) {
    
    this.mdmEntry = mdmEntry;
    return this;
  }

   /**
   * If the kind is a resolution by MDM entry then this is the name of MDM entry inside the definition.
   * @return mdmEntry
  **/
  @javax.annotation.Nullable

  @JsonProperty(MDM_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMdmEntry() {
    return mdmEntry;
  }


  @JsonProperty(MDM_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMdmEntry(String mdmEntry) {
    this.mdmEntry = mdmEntry;
  }


  public ValueTransformationConfigData mdmPropertyName(String mdmPropertyName) {
    
    this.mdmPropertyName = mdmPropertyName;
    return this;
  }

   /**
   * If the kind is a resolution by MDM entry then this is the name of MDM entry inside the definition.
   * @return mdmPropertyName
  **/
  @javax.annotation.Nullable

  @JsonProperty(MDM_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMdmPropertyName() {
    return mdmPropertyName;
  }


  @JsonProperty(MDM_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMdmPropertyName(String mdmPropertyName) {
    this.mdmPropertyName = mdmPropertyName;
  }


  public ValueTransformationConfigData transformation(InvocationRequest transformation) {
    
    this.transformation = transformation;
    return this;
  }

   /**
   * If the transformation is too complex then a transformation InvocationRequest can be defined let it be script or api call. 
   * @return transformation
  **/
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(TRANSFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvocationRequest getTransformation() {
    return transformation;
  }


  @JsonProperty(TRANSFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransformation(InvocationRequest transformation) {
    this.transformation = transformation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueTransformationConfigData valueTransformationConfigData = (ValueTransformationConfigData) o;
    return Objects.equals(this.name, valueTransformationConfigData.name) &&
        Objects.equals(this.kind, valueTransformationConfigData.kind) &&
        Objects.equals(this.mappings, valueTransformationConfigData.mappings) &&
        Objects.equals(this.mdmDefinition, valueTransformationConfigData.mdmDefinition) &&
        Objects.equals(this.mdmEntry, valueTransformationConfigData.mdmEntry) &&
        Objects.equals(this.mdmPropertyName, valueTransformationConfigData.mdmPropertyName) &&
        Objects.equals(this.transformation, valueTransformationConfigData.transformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, kind, mappings, mdmDefinition, mdmEntry, mdmPropertyName, transformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueTransformationConfigData {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("    mdmDefinition: ").append(toIndentedString(mdmDefinition)).append("\n");
    sb.append("    mdmEntry: ").append(toIndentedString(mdmEntry)).append("\n");
    sb.append("    mdmPropertyName: ").append(toIndentedString(mdmPropertyName)).append("\n");
    sb.append("    transformation: ").append(toIndentedString(transformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

