/*
 * smartbit4all navigation api
 * smartbit4all navigation api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.smartbit4all.api.navigation.bean;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.smartbit4all.api.navigation.bean.NavigationNode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The instance of a navigation that refers to navigation config and root nodes.
 */
@ApiModel(description = "The instance of a navigation that refers to navigation config and root nodes.")
@JsonPropertyOrder({
  Navigation.ROOTS,
  Navigation.CONFIG_URI
})
@JsonTypeName("Navigation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Navigation {
  public static final String ROOTS = "roots";
  private List<NavigationNode> roots = null;

  public static final String CONFIG_URI = "configUri";
  private URI configUri;


  public Navigation roots(List<NavigationNode> roots) {
    
    this.roots = roots;
    return this;
  }

  public Navigation addRootsItem(NavigationNode rootsItem) {
    if (this.roots == null) {
      this.roots = new ArrayList<>();
    }
    this.roots.add(rootsItem);
    return this;
  }

   /**
   * Get roots
   * @return roots
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(ROOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NavigationNode> getRoots() {
    return roots;
  }


  @JsonProperty(ROOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoots(List<NavigationNode> roots) {
    this.roots = roots;
  }


  public Navigation configUri(URI configUri) {
    
    this.configUri = configUri;
    return this;
  }

   /**
   * The uri of the configuration that drives the given navigation instance.
   * @return configUri
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "The uri of the configuration that drives the given navigation instance.")
  @JsonProperty(CONFIG_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getConfigUri() {
    return configUri;
  }


  @JsonProperty(CONFIG_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigUri(URI configUri) {
    this.configUri = configUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Navigation navigation = (Navigation) o;
    return Objects.equals(this.roots, navigation.roots) &&
        Objects.equals(this.configUri, navigation.configUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roots, configUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Navigation {\n");
    sb.append("    roots: ").append(toIndentedString(roots)).append("\n");
    sb.append("    configUri: ").append(toIndentedString(configUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

